#!/bin/bash
set -e

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )"
source ${DIR}/../../scripts/utils.sh

get_3rdparty_file "IBM-MQ-Install-Java-All.jar"

if [ ! -f ${DIR}/IBM-MQ-Install-Java-All.jar ]
then
     # not running with github actions
     logerror "ERROR: ${DIR}/IBM-MQ-Install-Java-All.jar is missing. It must be downloaded manually in order to acknowledge user agreement"
     exit 1
fi

if [ ! -f ${DIR}/com.ibm.mq.allclient.jar ]
then
     # install deps
     log "Getting com.ibm.mq.allclient.jar and jms.jar from IBM-MQ-Install-Java-All.jar"
     if [[ "$OSTYPE" == "darwin"* ]]
     then
          # workaround for issue on linux, see https://github.com/vdesabou/kafka-docker-playground/issues/851#issuecomment-821151962
          rm -rf ${DIR}/install/
     else
          sudo rm -rf ${DIR}/install/
     fi
     docker run --rm -v ${DIR}/IBM-MQ-Install-Java-All.jar:/tmp/IBM-MQ-Install-Java-All.jar -v ${DIR}/install:/tmp/install openjdk:8 java -jar /tmp/IBM-MQ-Install-Java-All.jar --acceptLicense /tmp/install
     cp ${DIR}/install/wmq/JavaSE/lib/jms.jar ${DIR}/
     cp ${DIR}/install/wmq/JavaSE/lib/com.ibm.mq.allclient.jar ${DIR}/
fi

${DIR}/../../environment/plaintext/start.sh "${PWD}/docker-compose.plaintext.repro-90709-error-mqrc-2009.yml"

log "Sending messages to topic sink-messages"
docker exec -i broker kafka-console-producer --broker-list broker:9092 --topic sink-messages << EOF
This is my message
EOF

curl --request PUT \
  --url http://localhost:8083/admin/loggers/io.confluent.connect.utils \
  --header 'Accept: application/json' \
  --header 'Content-Type: application/json' \
  --data '{
	"level": "TRACE"
}'

log "Creating IBM MQ source connector using zazkia"
curl -X PUT \
     -H "Content-Type: application/json" \
     --data '{
               "connector.class": "io.confluent.connect.jms.IbmMqSinkConnector",
                    "topics": "sink-messages",
                    "mq.hostname": "zazkia",
                    "mq.port": "49998",
                    "mq.transport.type": "client",
                    "mq.queue.manager": "QM1",
                    "mq.channel": "DEV.APP.SVRCONN",
                    "mq.username": "app",
                    "mq.password": "passw0rd",
                    "jms.destination.name": "DEV.QUEUE.1",
                    "jms.destination.type": "queue",
                    "value.converter": "org.apache.kafka.connect.storage.StringConverter",
                    "key.converter": "org.apache.kafka.connect.storage.StringConverter",
                    "confluent.license": "",
                    "confluent.topic.bootstrap.servers": "broker:9092",
                    "confluent.topic.replication.factor": "1"
          }' \
     http://localhost:8083/connectors/ibm-mq-sink4/config | jq .

log "Open zazkia UI is available on http://localhost:9191"
sleep 10

log "Verify message received in DEV.QUEUE.1 queue"
docker exec ibmmq bash -c "/opt/mqm/samp/bin/amqsbcg DEV.QUEUE.1" > /tmp/result.log  2>&1
cat /tmp/result.log
grep "my message" /tmp/result.log

log "now go to zazkia UI, click on <close all connnections> button"

check_if_continue

log "Sending messages to topic sink-messages"
docker exec -i broker kafka-console-producer --broker-list broker:9092 --topic sink-messages << EOF
This is my message after connection close
EOF

# [2022-02-04 14:32:45,821] DEBUG [ibm-mq-sink4|task-0] Start exponential (0-86400000 ms) backoff of 00:00:00.000 before another attempt (io.confluent.connect.utils.retry.RetryCounter:361)
# [2022-02-04 14:32:45,822] DEBUG [ibm-mq-sink4|task-0] Completed exponential (0-86400000 ms) backoff of 00:00:00.000 (io.confluent.connect.utils.retry.RetryCounter:373)
# [2022-02-04 14:32:45,822] WARN [ibm-mq-sink4|task-0] Could not produce message. Will retry for 60000 millis (io.confluent.connect.jms.BaseJmsSinkTask:182)
# com.ibm.msg.client.jms.DetailedJMSException: JMSWMQ2007: Failed to send a message to destination 'DEV.QUEUE.1'.
# JMS attempted to perform an MQPUT or MQPUT1; however IBM MQ reported an error.
# Use the linked exception to determine the cause of this error.
# 	at com.ibm.msg.client.wmq.common.internal.Reason.reasonToException(Reason.java:595)
# 	at com.ibm.msg.client.wmq.common.internal.Reason.createException(Reason.java:215)
# 	at com.ibm.msg.client.wmq.internal.WMQMessageProducer.checkJmqiCallSuccess(WMQMessageProducer.java:1293)
# 	at com.ibm.msg.client.wmq.internal.WMQMessageProducer.checkJmqiCallSuccess(WMQMessageProducer.java:1250)
# 	at com.ibm.msg.client.wmq.internal.WMQMessageProducer.access$800(WMQMessageProducer.java:76)
# 	at com.ibm.msg.client.wmq.internal.WMQMessageProducer$SpiIdentifiedProducerShadow.sendInternal(WMQMessageProducer.java:911)
# 	at com.ibm.msg.client.wmq.internal.WMQMessageProducer$ProducerShadow.send(WMQMessageProducer.java:567)
# 	at com.ibm.msg.client.wmq.internal.WMQMessageProducer.send(WMQMessageProducer.java:1433)
# 	at com.ibm.msg.client.jms.internal.JmsMessageProducerImpl.sendMessage(JmsMessageProducerImpl.java:855)
# 	at com.ibm.msg.client.jms.internal.JmsMessageProducerImpl.synchronousSendInternal(JmsMessageProducerImpl.java:2055)
# 	at com.ibm.msg.client.jms.internal.JmsMessageProducerImpl.sendInternal(JmsMessageProducerImpl.java:1993)
# 	at com.ibm.msg.client.jms.internal.JmsMessageProducerImpl.send(JmsMessageProducerImpl.java:1486)
# 	at com.ibm.mq.jms.MQMessageProducer.send(MQMessageProducer.java:293)
# 	at io.confluent.connect.jms.BaseJmsSinkTask.send(BaseJmsSinkTask.java:174)
# 	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
# 	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
# 	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655)
# 	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
# 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
# 	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
# 	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
# 	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
# 	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
# 	at io.confluent.connect.jms.BaseJmsSinkTask.put(BaseJmsSinkTask.java:111)
# 	at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:604)
# 	at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:334)
# 	at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:235)
# 	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:204)
# 	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:199)
# 	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:254)
# 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
# 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
# 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
# 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
# 	at java.base/java.lang.Thread.run(Thread.java:829)
# Caused by: com.ibm.mq.MQException: JMSCMQ0001: IBM MQ call failed with compcode '2' ('MQCC_FAILED') reason '2009' ('MQRC_CONNECTION_BROKEN').
# 	at com.ibm.msg.client.wmq.common.internal.Reason.createException(Reason.java:203)
# 	... 33 more
# Caused by: com.ibm.mq.jmqi.JmqiException: CC=2;RC=2009;AMQ9206: Error sending data to host 'zazkia/192.168.112.4:49998 (zazkia)'. [1=com.ibm.mq.jmqi.JmqiException[CC=2;RC=2009],3=zazkia/192.168.112.4:49998 (zazkia),4=TCP,5=RemoteTCPConnection.send(byte [ ],int,int,int,int)]
# 	at com.ibm.mq.jmqi.remote.impl.RemoteTCPConnection.send(RemoteTCPConnection.java:1708)
# 	at com.ibm.mq.jmqi.remote.impl.RemoteConnection.wrapSend(RemoteConnection.java:2976)
# 	at com.ibm.mq.jmqi.remote.impl.RemoteConnection.sendTSH(RemoteConnection.java:2742)
# 	at com.ibm.mq.jmqi.remote.impl.RemoteSession.sendTSH(RemoteSession.java:775)
# 	at com.ibm.mq.jmqi.remote.impl.RemoteSession.sendTSH(RemoteSession.java:691)
# 	at com.ibm.mq.jmqi.remote.api.RemoteFAP.jmqiPutMessageWithProps(RemoteFAP.java:8143)
# 	at com.ibm.mq.jmqi.remote.api.RemoteFAP.jmqiPut(RemoteFAP.java:7037)
# 	at com.ibm.mq.ese.jmqi.InterceptedJmqiImpl.jmqiPut(InterceptedJmqiImpl.java:636)
# 	at com.ibm.mq.ese.jmqi.ESEJMQI.jmqiPut(ESEJMQI.java:637)
# 	at com.ibm.msg.client.wmq.internal.WMQMessageProducer$SpiIdentifiedProducerShadow.sendInternal(WMQMessageProducer.java:897)
# 	... 29 more
# Caused by: com.ibm.mq.jmqi.JmqiException: CC=2;RC=2009
# 	at com.ibm.mq.jmqi.remote.impl.RemoteConnection.asyncConnectionBroken(RemoteConnection.java:3837)
# 	at com.ibm.mq.jmqi.remote.impl.RemoteRcvThread.run(RemoteRcvThread.java:587)
# 	at com.ibm.msg.client.commonservices.workqueue.WorkQueueItem.runTask(WorkQueueItem.java:319)
# 	at com.ibm.msg.client.commonservices.workqueue.SimpleWorkQueueItem.runItem(SimpleWorkQueueItem.java:99)
# 	at com.ibm.msg.client.commonservices.workqueue.WorkQueueItem.run(WorkQueueItem.java:343)
# 	at com.ibm.msg.client.commonservices.workqueue.WorkQueueManager.runWorkQueueItem(WorkQueueManager.java:312)
# 	at com.ibm.msg.client.commonservices.j2se.workqueue.WorkQueueManagerImplementation$ThreadPoolWorker.run(WorkQueueManagerImplementation.java:1227)
# Caused by: com.ibm.mq.jmqi.JmqiException: CC=2;RC=2009;AMQ9208: Error on receive from host 'zazkia/192.168.112.4:49998 (zazkia)'. [1=-1,2=ffffffff,3=zazkia/192.168.112.4:49998 (zazkia),4=TCP]
# 	at com.ibm.mq.jmqi.remote.impl.RemoteRcvThread.receiveBuffer(RemoteRcvThread.java:796)
# 	at com.ibm.mq.jmqi.remote.impl.RemoteRcvThread.receiveOneTSH(RemoteRcvThread.java:739)
# 	at com.ibm.mq.jmqi.remote.impl.RemoteRcvThread.run(RemoteRcvThread.java:156)
# 	... 5 more
# [2022-02-04 14:32:45,829] DEBUG [ibm-mq-sink4|task-0] Start exponential (0-86400000 ms) backoff of 00:00:00.000 before another attempt (io.confluent.connect.utils.retry.RetryCounter:361)
# [2022-02-04 14:32:45,829] DEBUG [ibm-mq-sink4|task-0] Completed exponential (0-86400000 ms) backoff of 00:00:00.000 (io.confluent.connect.utils.retry.RetryCounter:373)
# [2022-02-04 14:32:45,829] WARN [ibm-mq-sink4|task-0] Could not produce message. Will retry for 60000 millis (io.confluent.connect.jms.BaseJmsSinkTask:182)
# com.ibm.msg.client.jms.DetailedJMSException: JMSWMQ2007: Failed to send a message to destination 'DEV.QUEUE.1'.
# JMS attempted to perform an MQPUT or MQPUT1; however IBM MQ reported an error.
# Use the linked exception to determine the cause of this error.
# 	at com.ibm.msg.client.wmq.common.internal.Reason.reasonToException(Reason.java:595)
# 	at com.ibm.msg.client.wmq.common.internal.Reason.createException(Reason.java:215)
# 	at com.ibm.msg.client.wmq.internal.WMQMessageProducer.checkJmqiCallSuccess(WMQMessageProducer.java:1293)
# 	at com.ibm.msg.client.wmq.internal.WMQMessageProducer.checkJmqiCallSuccess(WMQMessageProducer.java:1250)
# 	at com.ibm.msg.client.wmq.internal.WMQMessageProducer.access$800(WMQMessageProducer.java:76)
# 	at com.ibm.msg.client.wmq.internal.WMQMessageProducer$SpiIdentifiedProducerShadow.sendInternal(WMQMessageProducer.java:911)
# 	at com.ibm.msg.client.wmq.internal.WMQMessageProducer$ProducerShadow.send(WMQMessageProducer.java:567)
# 	at com.ibm.msg.client.wmq.internal.WMQMessageProducer.send(WMQMessageProducer.java:1433)
# 	at com.ibm.msg.client.jms.internal.JmsMessageProducerImpl.sendMessage(JmsMessageProducerImpl.java:855)
# 	at com.ibm.msg.client.jms.internal.JmsMessageProducerImpl.synchronousSendInternal(JmsMessageProducerImpl.java:2055)
# 	at com.ibm.msg.client.jms.internal.JmsMessageProducerImpl.sendInternal(JmsMessageProducerImpl.java:1993)
# 	at com.ibm.msg.client.jms.internal.JmsMessageProducerImpl.send(JmsMessageProducerImpl.java:1486)
# 	at com.ibm.mq.jms.MQMessageProducer.send(MQMessageProducer.java:293)
# 	at io.confluent.connect.jms.BaseJmsSinkTask.send(BaseJmsSinkTask.java:174)
# 	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
# 	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
# 	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655)
# 	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
# 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
# 	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
# 	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
# 	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
# 	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
# 	at io.confluent.connect.jms.BaseJmsSinkTask.put(BaseJmsSinkTask.java:111)
# 	at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:604)
# 	at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:334)
# 	at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:235)
# 	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:204)
# 	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:199)
# 	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:254)
# 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
# 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
# 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
# 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
# 	at java.base/java.lang.Thread.run(Thread.java:829)
# Caused by: com.ibm.mq.MQException: JMSCMQ0001: IBM MQ call failed with compcode '2' ('MQCC_FAILED') reason '2009' ('MQRC_CONNECTION_BROKEN').
# 	at com.ibm.msg.client.wmq.common.internal.Reason.createException(Reason.java:203)
# 	... 33 more
# Caused by: com.ibm.mq.jmqi.JmqiException: CC=2;RC=2009;AMQ9206: Error sending data to host 'zazkia/192.168.112.4:49998 (zazkia)'. [1=com.ibm.mq.jmqi.JmqiException[CC=2;RC=2009],3=zazkia/192.168.112.4:49998 (zazkia),4=TCP,5=RemoteTCPConnection.send(byte [ ],int,int,int,int)]
# 	at com.ibm.mq.jmqi.remote.impl.RemoteTCPConnection.send(RemoteTCPConnection.java:1708)
# 	at com.ibm.mq.jmqi.remote.impl.RemoteConnection.wrapSend(RemoteConnection.java:2976)
# 	at com.ibm.mq.jmqi.remote.impl.RemoteConnection.sendTSH(RemoteConnection.java:2742)
# 	at com.ibm.mq.jmqi.remote.impl.RemoteSession.sendTSH(RemoteSession.java:775)
# 	at com.ibm.mq.jmqi.remote.impl.RemoteSession.sendTSH(RemoteSession.java:691)
# 	at com.ibm.mq.jmqi.remote.api.RemoteFAP.jmqiPutMessageWithProps(RemoteFAP.java:8143)
# 	at com.ibm.mq.jmqi.remote.api.RemoteFAP.jmqiPut(RemoteFAP.java:7037)
# 	at com.ibm.mq.ese.jmqi.InterceptedJmqiImpl.jmqiPut(InterceptedJmqiImpl.java:636)
# 	at com.ibm.mq.ese.jmqi.ESEJMQI.jmqiPut(ESEJMQI.java:637)
# 	at com.ibm.msg.client.wmq.internal.WMQMessageProducer$SpiIdentifiedProducerShadow.sendInternal(WMQMessageProducer.java:897)
# 	... 29 more
# Caused by: com.ibm.mq.jmqi.JmqiException: CC=2;RC=2009
# 	at com.ibm.mq.jmqi.remote.impl.RemoteConnection.asyncConnectionBroken(RemoteConnection.java:3837)
# 	at com.ibm.mq.jmqi.remote.impl.RemoteRcvThread.run(RemoteRcvThread.java:587)
# 	at com.ibm.msg.client.commonservices.workqueue.WorkQueueItem.runTask(WorkQueueItem.java:319)
# 	at com.ibm.msg.client.commonservices.workqueue.SimpleWorkQueueItem.runItem(SimpleWorkQueueItem.java:99)
# 	at com.ibm.msg.client.commonservices.workqueue.WorkQueueItem.run(WorkQueueItem.java:343)
# 	at com.ibm.msg.client.commonservices.workqueue.WorkQueueManager.runWorkQueueItem(WorkQueueManager.java:312)
# 	at com.ibm.msg.client.commonservices.j2se.workqueue.WorkQueueManagerImplementation$ThreadPoolWorker.run(WorkQueueManagerImplementation.java:1227)
# Caused by: com.ibm.mq.jmqi.JmqiException: CC=2;RC=2009;AMQ9208: Error on receive from host 'zazkia/192.168.112.4:49998 (zazkia)'. [1=-1,2=ffffffff,3=zazkia/192.168.112.4:49998 (zazkia),4=TCP]
# 	at com.ibm.mq.jmqi.remote.impl.RemoteRcvThread.receiveBuffer(RemoteRcvThread.java:796)
# 	at com.ibm.mq.jmqi.remote.impl.RemoteRcvThread.receiveOneTSH(RemoteRcvThread.java:739)
# 	at com.ibm.mq.jmqi.remote.impl.RemoteRcvThread.run(RemoteRcvThread.java:156)
# 	... 5 more
# [2022-02-04 14:32:45,835] DEBUG [ibm-mq-sink4|task-0] Start exponential (0-86400000 ms) backoff of 00:00:00.001 before another attempt (io.confluent.connect.utils.retry.RetryCounter:361)
# [2022-02-04 14:32:45,835] TRACE [ibm-mq-sink4|task-0] Sleeping for 00:00:00.001ms, 1ms remaining (io.confluent.connect.utils.retry.RetryCounter:412)
# [2022-02-04 14:32:45,837] DEBUG [ibm-mq-sink4|task-0] Completed exponential (0-86400000 ms) backoff of 00:00:00.001 (io.confluent.connect.utils.retry.RetryCounter:373)
# [2022-02-04 14:32:45,837] WARN [ibm-mq-sink4|task-0] Could not produce message. Will retry for 60000 millis (io.confluent.connect.jms.BaseJmsSinkTask:182)
# com.ibm.msg.client.jms.DetailedJMSException: JMSWMQ2007: Failed to send a message to destination 'DEV.QUEUE.1'.
# JMS attempted to perform an MQPUT or MQPUT1; however IBM MQ reported an error.
# Use the linked exception to determine the cause of this error.
# 	at com.ibm.msg.client.wmq.common.internal.Reason.reasonToException(Reason.java:595)
# 	at com.ibm.msg.client.wmq.common.internal.Reason.createException(Reason.java:215)
# 	at com.ibm.msg.client.wmq.internal.WMQMessageProducer.checkJmqiCallSuccess(WMQMessageProducer.java:1293)
# 	at com.ibm.msg.client.wmq.internal.WMQMessageProducer.checkJmqiCallSuccess(WMQMessageProducer.java:1250)
# 	at com.ibm.msg.client.wmq.internal.WMQMessageProducer.access$800(WMQMessageProducer.java:76)
# 	at com.ibm.msg.client.wmq.internal.WMQMessageProducer$SpiIdentifiedProducerShadow.sendInternal(WMQMessageProducer.java:911)
# 	at com.ibm.msg.client.wmq.internal.WMQMessageProducer$ProducerShadow.send(WMQMessageProducer.java:567)
# 	at com.ibm.msg.client.wmq.internal.WMQMessageProducer.send(WMQMessageProducer.java:1433)
# 	at com.ibm.msg.client.jms.internal.JmsMessageProducerImpl.sendMessage(JmsMessageProducerImpl.java:855)
# 	at com.ibm.msg.client.jms.internal.JmsMessageProducerImpl.synchronousSendInternal(JmsMessageProducerImpl.java:2055)
# 	at com.ibm.msg.client.jms.internal.JmsMessageProducerImpl.sendInternal(JmsMessageProducerImpl.java:1993)
# 	at com.ibm.msg.client.jms.internal.JmsMessageProducerImpl.send(JmsMessageProducerImpl.java:1486)
# 	at com.ibm.mq.jms.MQMessageProducer.send(MQMessageProducer.java:293)
# 	at io.confluent.connect.jms.BaseJmsSinkTask.send(BaseJmsSinkTask.java:174)
# 	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
# 	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
# 	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655)
# 	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
# 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
# 	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
# 	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
# 	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
# 	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
# 	at io.confluent.connect.jms.BaseJmsSinkTask.put(BaseJmsSinkTask.java:111)
# 	at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:604)
# 	at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:334)
# 	at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:235)
# 	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:204)
# 	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:199)
# 	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:254)
# 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
# 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
# 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
# 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
# 	at java.base/java.lang.Thread.run(Thread.java:829)
# Caused by: com.ibm.mq.MQException: JMSCMQ0001: IBM MQ call failed with compcode '2' ('MQCC_FAILED') reason '2009' ('MQRC_CONNECTION_BROKEN').
# 	at com.ibm.msg.client.wmq.common.internal.Reason.createException(Reason.java:203)
# 	... 33 more
# Caused by: com.ibm.mq.jmqi.JmqiException: CC=2;RC=2009;AMQ9206: Error sending data to host 'zazkia/192.168.112.4:49998 (zazkia)'. [1=com.ibm.mq.jmqi.JmqiException[CC=2;RC=2009],3=zazkia/192.168.112.4:49998 (zazkia),4=TCP,5=RemoteTCPConnection.send(byte [ ],int,int,int,int)]
# 	at com.ibm.mq.jmqi.remote.impl.RemoteTCPConnection.send(RemoteTCPConnection.java:1708)
# 	at com.ibm.mq.jmqi.remote.impl.RemoteConnection.wrapSend(RemoteConnection.java:2976)
# 	at com.ibm.mq.jmqi.remote.impl.RemoteConnection.sendTSH(RemoteConnection.java:2742)
# 	at com.ibm.mq.jmqi.remote.impl.RemoteSession.sendTSH(RemoteSession.java:775)
# 	at com.ibm.mq.jmqi.remote.impl.RemoteSession.sendTSH(RemoteSession.java:691)
# 	at com.ibm.mq.jmqi.remote.api.RemoteFAP.jmqiPutMessageWithProps(RemoteFAP.java:8143)
# 	at com.ibm.mq.jmqi.remote.api.RemoteFAP.jmqiPut(RemoteFAP.java:7037)
# 	at com.ibm.mq.ese.jmqi.InterceptedJmqiImpl.jmqiPut(InterceptedJmqiImpl.java:636)
# 	at com.ibm.mq.ese.jmqi.ESEJMQI.jmqiPut(ESEJMQI.java:637)
# 	at com.ibm.msg.client.wmq.internal.WMQMessageProducer$SpiIdentifiedProducerShadow.sendInternal(WMQMessageProducer.java:897)
# 	... 29 more
# Caused by: com.ibm.mq.jmqi.JmqiException: CC=2;RC=2009
# 	at com.ibm.mq.jmqi.remote.impl.RemoteConnection.asyncConnectionBroken(RemoteConnection.java:3837)
# 	at com.ibm.mq.jmqi.remote.impl.RemoteRcvThread.run(RemoteRcvThread.java:587)
# 	at com.ibm.msg.client.commonservices.workqueue.WorkQueueItem.runTask(WorkQueueItem.java:319)
# 	at com.ibm.msg.client.commonservices.workqueue.SimpleWorkQueueItem.runItem(SimpleWorkQueueItem.java:99)
# 	at com.ibm.msg.client.commonservices.workqueue.WorkQueueItem.run(WorkQueueItem.java:343)
# 	at com.ibm.msg.client.commonservices.workqueue.WorkQueueManager.runWorkQueueItem(WorkQueueManager.java:312)
# 	at com.ibm.msg.client.commonservices.j2se.workqueue.WorkQueueManagerImplementation$ThreadPoolWorker.run(WorkQueueManagerImplementation.java:1227)
# Caused by: com.ibm.mq.jmqi.JmqiException: CC=2;RC=2009;AMQ9208: Error on receive from host 'zazkia/192.168.112.4:49998 (zazkia)'. [1=-1,2=ffffffff,3=zazkia/192.168.112.4:49998 (zazkia),4=TCP]
# 	at com.ibm.mq.jmqi.remote.impl.RemoteRcvThread.receiveBuffer(RemoteRcvThread.java:796)
# 	at com.ibm.mq.jmqi.remote.impl.RemoteRcvThread.receiveOneTSH(RemoteRcvThread.java:739)
# 	at com.ibm.mq.jmqi.remote.impl.RemoteRcvThread.run(RemoteRcvThread.java:156)
# 	... 5 more
# [2022-02-04 14:32:45,842] DEBUG [ibm-mq-sink4|task-0] Start exponential (0-86400000 ms) backoff of 00:00:00.004 before another attempt (io.confluent.connect.utils.retry.RetryCounter:361)
# [2022-02-04 14:32:45,842] TRACE [ibm-mq-sink4|task-0] Sleeping for 00:00:00.004ms, 4ms remaining (io.confluent.connect.utils.retry.RetryCounter:412)
# [2022-02-04 14:32:45,846] DEBUG [ibm-mq-sink4|task-0] Completed exponential (0-86400000 ms) backoff of 00:00:00.004 (io.confluent.connect.utils.retry.RetryCounter:373)
# [2022-02-04 14:32:45,846] WARN [ibm-mq-sink4|task-0] Could not produce message. Will retry for 60000 millis (io.confluent.connect.jms.BaseJmsSinkTask:182)
# com.ibm.msg.client.jms.DetailedJMSException: JMSWMQ2007: Failed to send a message to destination 'DEV.QUEUE.1'.
# JMS attempted to perform an MQPUT or MQPUT1; however IBM MQ reported an error.
# Use the linked exception to determine the cause of this error.
# 	at com.ibm.msg.client.wmq.common.internal.Reason.reasonToException(Reason.java:595)
# 	at com.ibm.msg.client.wmq.common.internal.Reason.createException(Reason.java:215)
# 	at com.ibm.msg.client.wmq.internal.WMQMessageProducer.checkJmqiCallSuccess(WMQMessageProducer.java:1293)
# 	at com.ibm.msg.client.wmq.internal.WMQMessageProducer.checkJmqiCallSuccess(WMQMessageProducer.java:1250)
# 	at com.ibm.msg.client.wmq.internal.WMQMessageProducer.access$800(WMQMessageProducer.java:76)
# 	at com.ibm.msg.client.wmq.internal.WMQMessageProducer$SpiIdentifiedProducerShadow.sendInternal(WMQMessageProducer.java:911)
# 	at com.ibm.msg.client.wmq.internal.WMQMessageProducer$ProducerShadow.send(WMQMessageProducer.java:567)
# 	at com.ibm.msg.client.wmq.internal.WMQMessageProducer.send(WMQMessageProducer.java:1433)
# 	at com.ibm.msg.client.jms.internal.JmsMessageProducerImpl.sendMessage(JmsMessageProducerImpl.java:855)
# 	at com.ibm.msg.client.jms.internal.JmsMessageProducerImpl.synchronousSendInternal(JmsMessageProducerImpl.java:2055)
# 	at com.ibm.msg.client.jms.internal.JmsMessageProducerImpl.sendInternal(JmsMessageProducerImpl.java:1993)
# 	at com.ibm.msg.client.jms.internal.JmsMessageProducerImpl.send(JmsMessageProducerImpl.java:1486)
# 	at com.ibm.mq.jms.MQMessageProducer.send(MQMessageProducer.java:293)
# 	at io.confluent.connect.jms.BaseJmsSinkTask.send(BaseJmsSinkTask.java:174)
# 	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
# 	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
# 	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655)
# 	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
# 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
# 	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
# 	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
# 	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
# 	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
# 	at io.confluent.connect.jms.BaseJmsSinkTask.put(BaseJmsSinkTask.java:111)
# 	at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:604)
# 	at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:334)
# 	at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:235)
# 	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:204)
# 	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:199)
# 	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:254)
# 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
# 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
# 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
# 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
# 	at java.base/java.lang.Thread.run(Thread.java:829)
# Caused by: com.ibm.mq.MQException: JMSCMQ0001: IBM MQ call failed with compcode '2' ('MQCC_FAILED') reason '2009' ('MQRC_CONNECTION_BROKEN').
# 	at com.ibm.msg.client.wmq.common.internal.Reason.createException(Reason.java:203)
# 	... 33 more
# Caused by: com.ibm.mq.jmqi.JmqiException: CC=2;RC=2009;AMQ9206: Error sending data to host 'zazkia/192.168.112.4:49998 (zazkia)'. [1=com.ibm.mq.jmqi.JmqiException[CC=2;RC=2009],3=zazkia/192.168.112.4:49998 (zazkia),4=TCP,5=RemoteTCPConnection.send(byte [ ],int,int,int,int)]
# 	at com.ibm.mq.jmqi.remote.impl.RemoteTCPConnection.send(RemoteTCPConnection.java:1708)
# 	at com.ibm.mq.jmqi.remote.impl.RemoteConnection.wrapSend(RemoteConnection.java:2976)
# 	at com.ibm.mq.jmqi.remote.impl.RemoteConnection.sendTSH(RemoteConnection.java:2742)
# 	at com.ibm.mq.jmqi.remote.impl.RemoteSession.sendTSH(RemoteSession.java:775)
# 	at com.ibm.mq.jmqi.remote.impl.RemoteSession.sendTSH(RemoteSession.java:691)
# 	at com.ibm.mq.jmqi.remote.api.RemoteFAP.jmqiPutMessageWithProps(RemoteFAP.java:8143)
# 	at com.ibm.mq.jmqi.remote.api.RemoteFAP.jmqiPut(RemoteFAP.java:7037)
# 	at com.ibm.mq.ese.jmqi.InterceptedJmqiImpl.jmqiPut(InterceptedJmqiImpl.java:636)
# 	at com.ibm.mq.ese.jmqi.ESEJMQI.jmqiPut(ESEJMQI.java:637)
# 	at com.ibm.msg.client.wmq.internal.WMQMessageProducer$SpiIdentifiedProducerShadow.sendInternal(WMQMessageProducer.java:897)
# 	... 29 more
# Caused by: com.ibm.mq.jmqi.JmqiException: CC=2;RC=2009
# 	at com.ibm.mq.jmqi.remote.impl.RemoteConnection.asyncConnectionBroken(RemoteConnection.java:3837)
# 	at com.ibm.mq.jmqi.remote.impl.RemoteRcvThread.run(RemoteRcvThread.java:587)
# 	at com.ibm.msg.client.commonservices.workqueue.WorkQueueItem.runTask(WorkQueueItem.java:319)
# 	at com.ibm.msg.client.commonservices.workqueue.SimpleWorkQueueItem.runItem(SimpleWorkQueueItem.java:99)
# 	at com.ibm.msg.client.commonservices.workqueue.WorkQueueItem.run(WorkQueueItem.java:343)
# 	at com.ibm.msg.client.commonservices.workqueue.WorkQueueManager.runWorkQueueItem(WorkQueueManager.java:312)
# 	at com.ibm.msg.client.commonservices.j2se.workqueue.WorkQueueManagerImplementation$ThreadPoolWorker.run(WorkQueueManagerImplementation.java:1227)
# Caused by: com.ibm.mq.jmqi.JmqiException: CC=2;RC=2009;AMQ9208: Error on receive from host 'zazkia/192.168.112.4:49998 (zazkia)'. [1=-1,2=ffffffff,3=zazkia/192.168.112.4:49998 (zazkia),4=TCP]
# 	at com.ibm.mq.jmqi.remote.impl.RemoteRcvThread.receiveBuffer(RemoteRcvThread.java:796)
# 	at com.ibm.mq.jmqi.remote.impl.RemoteRcvThread.receiveOneTSH(RemoteRcvThread.java:739)
# 	at com.ibm.mq.jmqi.remote.impl.RemoteRcvThread.run(RemoteRcvThread.java:156)
# 	... 5 more
# [2022-02-04 14:32:45,852] DEBUG [ibm-mq-sink4|task-0] Start exponential (0-86400000 ms) backoff of 00:00:00.015 before another attempt (io.confluent.connect.utils.retry.RetryCounter:361)
# [2022-02-04 14:32:45,852] TRACE [ibm-mq-sink4|task-0] Sleeping for 00:00:00.015ms, 15ms remaining (io.confluent.connect.utils.retry.RetryCounter:412)
# [2022-02-04 14:32:45,868] DEBUG [ibm-mq-sink4|task-0] Completed exponential (0-86400000 ms) backoff of 00:00:00.015 (io.confluent.connect.utils.retry.RetryCounter:373)
# [2022-02-04 14:32:45,868] WARN [ibm-mq-sink4|task-0] Could not produce message. Will retry for 60000 millis (io.confluent.connect.jms.BaseJmsSinkTask:182)
# com.ibm.msg.client.jms.DetailedJMSException: JMSWMQ2007: Failed to send a message to destination 'DEV.QUEUE.1'.
# JMS attempted to perform an MQPUT or MQPUT1; however IBM MQ reported an error.
# Use the linked exception to determine the cause of this error.
# 	at com.ibm.msg.client.wmq.common.internal.Reason.reasonToException(Reason.java:595)
# 	at com.ibm.msg.client.wmq.common.internal.Reason.createException(Reason.java:215)
# 	at com.ibm.msg.client.wmq.internal.WMQMessageProducer.checkJmqiCallSuccess(WMQMessageProducer.java:1293)
# 	at com.ibm.msg.client.wmq.internal.WMQMessageProducer.checkJmqiCallSuccess(WMQMessageProducer.java:1250)
# 	at com.ibm.msg.client.wmq.internal.WMQMessageProducer.access$800(WMQMessageProducer.java:76)
# 	at com.ibm.msg.client.wmq.internal.WMQMessageProducer$SpiIdentifiedProducerShadow.sendInternal(WMQMessageProducer.java:911)
# 	at com.ibm.msg.client.wmq.internal.WMQMessageProducer$ProducerShadow.send(WMQMessageProducer.java:567)
# 	at com.ibm.msg.client.wmq.internal.WMQMessageProducer.send(WMQMessageProducer.java:1433)
# 	at com.ibm.msg.client.jms.internal.JmsMessageProducerImpl.sendMessage(JmsMessageProducerImpl.java:855)
# 	at com.ibm.msg.client.jms.internal.JmsMessageProducerImpl.synchronousSendInternal(JmsMessageProducerImpl.java:2055)
# 	at com.ibm.msg.client.jms.internal.JmsMessageProducerImpl.sendInternal(JmsMessageProducerImpl.java:1993)
# 	at com.ibm.msg.client.jms.internal.JmsMessageProducerImpl.send(JmsMessageProducerImpl.java:1486)
# 	at com.ibm.mq.jms.MQMessageProducer.send(MQMessageProducer.java:293)
# 	at io.confluent.connect.jms.BaseJmsSinkTask.send(BaseJmsSinkTask.java:174)
# 	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
# 	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
# 	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655)
# 	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
# 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
# 	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
# 	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
# 	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
# 	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
# 	at io.confluent.connect.jms.BaseJmsSinkTask.put(BaseJmsSinkTask.java:111)
# 	at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:604)
# 	at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:334)
# 	at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:235)
# 	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:204)
# 	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:199)
# 	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:254)
# 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
# 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
# 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
# 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
# 	at java.base/java.lang.Thread.run(Thread.java:829)
# Caused by: com.ibm.mq.MQException: JMSCMQ0001: IBM MQ call failed with compcode '2' ('MQCC_FAILED') reason '2009' ('MQRC_CONNECTION_BROKEN').
# 	at com.ibm.msg.client.wmq.common.internal.Reason.createException(Reason.java:203)
# 	... 33 more
# Caused by: com.ibm.mq.jmqi.JmqiException: CC=2;RC=2009;AMQ9206: Error sending data to host 'zazkia/192.168.112.4:49998 (zazkia)'. [1=com.ibm.mq.jmqi.JmqiException[CC=2;RC=2009],3=zazkia/192.168.112.4:49998 (zazkia),4=TCP,5=RemoteTCPConnection.send(byte [ ],int,int,int,int)]
# 	at com.ibm.mq.jmqi.remote.impl.RemoteTCPConnection.send(RemoteTCPConnection.java:1708)
# 	at com.ibm.mq.jmqi.remote.impl.RemoteConnection.wrapSend(RemoteConnection.java:2976)
# 	at com.ibm.mq.jmqi.remote.impl.RemoteConnection.sendTSH(RemoteConnection.java:2742)
# 	at com.ibm.mq.jmqi.remote.impl.RemoteSession.sendTSH(RemoteSession.java:775)
# 	at com.ibm.mq.jmqi.remote.impl.RemoteSession.sendTSH(RemoteSession.java:691)
# 	at com.ibm.mq.jmqi.remote.api.RemoteFAP.jmqiPutMessageWithProps(RemoteFAP.java:8143)
# 	at com.ibm.mq.jmqi.remote.api.RemoteFAP.jmqiPut(RemoteFAP.java:7037)
# 	at com.ibm.mq.ese.jmqi.InterceptedJmqiImpl.jmqiPut(InterceptedJmqiImpl.java:636)
# 	at com.ibm.mq.ese.jmqi.ESEJMQI.jmqiPut(ESEJMQI.java:637)
# 	at com.ibm.msg.client.wmq.internal.WMQMessageProducer$SpiIdentifiedProducerShadow.sendInternal(WMQMessageProducer.java:897)
# 	... 29 more
# Caused by: com.ibm.mq.jmqi.JmqiException: CC=2;RC=2009
# 	at com.ibm.mq.jmqi.remote.impl.RemoteConnection.asyncConnectionBroken(RemoteConnection.java:3837)
# 	at com.ibm.mq.jmqi.remote.impl.RemoteRcvThread.run(RemoteRcvThread.java:587)
# 	at com.ibm.msg.client.commonservices.workqueue.WorkQueueItem.runTask(WorkQueueItem.java:319)
# 	at com.ibm.msg.client.commonservices.workqueue.SimpleWorkQueueItem.runItem(SimpleWorkQueueItem.java:99)
# 	at com.ibm.msg.client.commonservices.workqueue.WorkQueueItem.run(WorkQueueItem.java:343)
# 	at com.ibm.msg.client.commonservices.workqueue.WorkQueueManager.runWorkQueueItem(WorkQueueManager.java:312)
# 	at com.ibm.msg.client.commonservices.j2se.workqueue.WorkQueueManagerImplementation$ThreadPoolWorker.run(WorkQueueManagerImplementation.java:1227)
# Caused by: com.ibm.mq.jmqi.JmqiException: CC=2;RC=2009;AMQ9208: Error on receive from host 'zazkia/192.168.112.4:49998 (zazkia)'. [1=-1,2=ffffffff,3=zazkia/192.168.112.4:49998 (zazkia),4=TCP]
# 	at com.ibm.mq.jmqi.remote.impl.RemoteRcvThread.receiveBuffer(RemoteRcvThread.java:796)
# 	at com.ibm.mq.jmqi.remote.impl.RemoteRcvThread.receiveOneTSH(RemoteRcvThread.java:739)
# 	at com.ibm.mq.jmqi.remote.impl.RemoteRcvThread.run(RemoteRcvThread.java:156)
# 	... 5 more
# [2022-02-04 14:32:45,872] DEBUG [ibm-mq-sink4|task-0] Start exponential (0-86400000 ms) backoff of 00:00:00.000 before another attempt (io.confluent.connect.utils.retry.RetryCounter:361)
# [2022-02-04 14:32:45,873] DEBUG [ibm-mq-sink4|task-0] Completed exponential (0-86400000 ms) backoff of 00:00:00.000 (io.confluent.connect.utils.retry.RetryCounter:373)
# [2022-02-04 14:32:45,873] WARN [ibm-mq-sink4|task-0] Could not produce message. Will retry for 60000 millis (io.confluent.connect.jms.BaseJmsSinkTask:182)
# com.ibm.msg.client.jms.DetailedJMSException: JMSWMQ2007: Failed to send a message to destination 'DEV.QUEUE.1'.
# JMS attempted to perform an MQPUT or MQPUT1; however IBM MQ reported an error.
# Use the linked exception to determine the cause of this error.
# 	at com.ibm.msg.client.wmq.common.internal.Reason.reasonToException(Reason.java:595)
# 	at com.ibm.msg.client.wmq.common.internal.Reason.createException(Reason.java:215)
# 	at com.ibm.msg.client.wmq.internal.WMQMessageProducer.checkJmqiCallSuccess(WMQMessageProducer.java:1293)
# 	at com.ibm.msg.client.wmq.internal.WMQMessageProducer.checkJmqiCallSuccess(WMQMessageProducer.java:1250)
# 	at com.ibm.msg.client.wmq.internal.WMQMessageProducer.access$800(WMQMessageProducer.java:76)
# 	at com.ibm.msg.client.wmq.internal.WMQMessageProducer$SpiIdentifiedProducerShadow.sendInternal(WMQMessageProducer.java:911)
# 	at com.ibm.msg.client.wmq.internal.WMQMessageProducer$ProducerShadow.send(WMQMessageProducer.java:567)
# 	at com.ibm.msg.client.wmq.internal.WMQMessageProducer.send(WMQMessageProducer.java:1433)
# 	at com.ibm.msg.client.jms.internal.JmsMessageProducerImpl.sendMessage(JmsMessageProducerImpl.java:855)
# 	at com.ibm.msg.client.jms.internal.JmsMessageProducerImpl.synchronousSendInternal(JmsMessageProducerImpl.java:2055)
# 	at com.ibm.msg.client.jms.internal.JmsMessageProducerImpl.sendInternal(JmsMessageProducerImpl.java:1993)
# 	at com.ibm.msg.client.jms.internal.JmsMessageProducerImpl.send(JmsMessageProducerImpl.java:1486)
# 	at com.ibm.mq.jms.MQMessageProducer.send(MQMessageProducer.java:293)
# 	at io.confluent.connect.jms.BaseJmsSinkTask.send(BaseJmsSinkTask.java:174)
# 	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
# 	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
# 	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655)
# 	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
# 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
# 	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
# 	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
# 	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
# 	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
# 	at io.confluent.connect.jms.BaseJmsSinkTask.put(BaseJmsSinkTask.java:111)
# 	at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:604)
# 	at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:334)
# 	at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:235)
# 	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:204)
# 	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:199)
# 	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:254)
# 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
# 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
# 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
# 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
# 	at java.base/java.lang.Thread.run(Thread.java:829)
# Caused by: com.ibm.mq.MQException: JMSCMQ0001: IBM MQ call failed with compcode '2' ('MQCC_FAILED') reason '2009' ('MQRC_CONNECTION_BROKEN').
# 	at com.ibm.msg.client.wmq.common.internal.Reason.createException(Reason.java:203)
# 	... 33 more
# Caused by: com.ibm.mq.jmqi.JmqiException: CC=2;RC=2009;AMQ9206: Error sending data to host 'zazkia/192.168.112.4:49998 (zazkia)'. [1=com.ibm.mq.jmqi.JmqiException[CC=2;RC=2009],3=zazkia/192.168.112.4:49998 (zazkia),4=TCP,5=RemoteTCPConnection.send(byte [ ],int,int,int,int)]
# 	at com.ibm.mq.jmqi.remote.impl.RemoteTCPConnection.send(RemoteTCPConnection.java:1708)
# 	at com.ibm.mq.jmqi.remote.impl.RemoteConnection.wrapSend(RemoteConnection.java:2976)
# 	at com.ibm.mq.jmqi.remote.impl.RemoteConnection.sendTSH(RemoteConnection.java:2742)
# 	at com.ibm.mq.jmqi.remote.impl.RemoteSession.sendTSH(RemoteSession.java:775)
# 	at com.ibm.mq.jmqi.remote.impl.RemoteSession.sendTSH(RemoteSession.java:691)
# 	at com.ibm.mq.jmqi.remote.api.RemoteFAP.jmqiPutMessageWithProps(RemoteFAP.java:8143)
# 	at com.ibm.mq.jmqi.remote.api.RemoteFAP.jmqiPut(RemoteFAP.java:7037)
# 	at com.ibm.mq.ese.jmqi.InterceptedJmqiImpl.jmqiPut(InterceptedJmqiImpl.java:636)
# 	at com.ibm.mq.ese.jmqi.ESEJMQI.jmqiPut(ESEJMQI.java:637)
# 	at com.ibm.msg.client.wmq.internal.WMQMessageProducer$SpiIdentifiedProducerShadow.sendInternal(WMQMessageProducer.java:897)
# 	... 29 more
# Caused by: com.ibm.mq.jmqi.JmqiException: CC=2;RC=2009
# 	at com.ibm.mq.jmqi.remote.impl.RemoteConnection.asyncConnectionBroken(RemoteConnection.java:3837)
# 	at com.ibm.mq.jmqi.remote.impl.RemoteRcvThread.run(RemoteRcvThread.java:587)
# 	at com.ibm.msg.client.commonservices.workqueue.WorkQueueItem.runTask(WorkQueueItem.java:319)
# 	at com.ibm.msg.client.commonservices.workqueue.SimpleWorkQueueItem.runItem(SimpleWorkQueueItem.java:99)
# 	at com.ibm.msg.client.commonservices.workqueue.WorkQueueItem.run(WorkQueueItem.java:343)
# 	at com.ibm.msg.client.commonservices.workqueue.WorkQueueManager.runWorkQueueItem(WorkQueueManager.java:312)
# 	at com.ibm.msg.client.commonservices.j2se.workqueue.WorkQueueManagerImplementation$ThreadPoolWorker.run(WorkQueueManagerImplementation.java:1227)
# Caused by: com.ibm.mq.jmqi.JmqiException: CC=2;RC=2009;AMQ9208: Error on receive from host 'zazkia/192.168.112.4:49998 (zazkia)'. [1=-1,2=ffffffff,3=zazkia/192.168.112.4:49998 (zazkia),4=TCP]
# 	at com.ibm.mq.jmqi.remote.impl.RemoteRcvThread.receiveBuffer(RemoteRcvThread.java:796)
# 	at com.ibm.mq.jmqi.remote.impl.RemoteRcvThread.receiveOneTSH(RemoteRcvThread.java:739)
# 	at com.ibm.mq.jmqi.remote.impl.RemoteRcvThread.run(RemoteRcvThread.java:156)
# 	... 5 more
# [2022-02-04 14:32:45,882] DEBUG [ibm-mq-sink4|task-0] Start exponential (0-86400000 ms) backoff of 00:00:00.044 before another attempt (io.confluent.connect.utils.retry.RetryCounter:361)
# [2022-02-04 14:32:45,882] TRACE [ibm-mq-sink4|task-0] Sleeping for 00:00:00.044ms, 44ms remaining (io.confluent.connect.utils.retry.RetryCounter:412)
# [2022-02-04 14:32:45,927] DEBUG [ibm-mq-sink4|task-0] Completed exponential (0-86400000 ms) backoff of 00:00:00.044 (io.confluent.connect.utils.retry.RetryCounter:373)
# [2022-02-04 14:32:45,927] WARN [ibm-mq-sink4|task-0] Could not produce message. Will retry for 60000 millis (io.confluent.connect.jms.BaseJmsSinkTask:182)
# com.ibm.msg.client.jms.DetailedJMSException: JMSWMQ2007: Failed to send a message to destination 'DEV.QUEUE.1'.
# JMS attempted to perform an MQPUT or MQPUT1; however IBM MQ reported an error.
# Use the linked exception to determine the cause of this error.
# 	at com.ibm.msg.client.wmq.common.internal.Reason.reasonToException(Reason.java:595)
# 	at com.ibm.msg.client.wmq.common.internal.Reason.createException(Reason.java:215)
# 	at com.ibm.msg.client.wmq.internal.WMQMessageProducer.checkJmqiCallSuccess(WMQMessageProducer.java:1293)
# 	at com.ibm.msg.client.wmq.internal.WMQMessageProducer.checkJmqiCallSuccess(WMQMessageProducer.java:1250)
# 	at com.ibm.msg.client.wmq.internal.WMQMessageProducer.access$800(WMQMessageProducer.java:76)
# 	at com.ibm.msg.client.wmq.internal.WMQMessageProducer$SpiIdentifiedProducerShadow.sendInternal(WMQMessageProducer.java:911)
# 	at com.ibm.msg.client.wmq.internal.WMQMessageProducer$ProducerShadow.send(WMQMessageProducer.java:567)
# 	at com.ibm.msg.client.wmq.internal.WMQMessageProducer.send(WMQMessageProducer.java:1433)
# 	at com.ibm.msg.client.jms.internal.JmsMessageProducerImpl.sendMessage(JmsMessageProducerImpl.java:855)
# 	at com.ibm.msg.client.jms.internal.JmsMessageProducerImpl.synchronousSendInternal(JmsMessageProducerImpl.java:2055)
# 	at com.ibm.msg.client.jms.internal.JmsMessageProducerImpl.sendInternal(JmsMessageProducerImpl.java:1993)
# 	at com.ibm.msg.client.jms.internal.JmsMessageProducerImpl.send(JmsMessageProducerImpl.java:1486)
# 	at com.ibm.mq.jms.MQMessageProducer.send(MQMessageProducer.java:293)
# 	at io.confluent.connect.jms.BaseJmsSinkTask.send(BaseJmsSinkTask.java:174)
# 	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
# 	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
# 	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655)
# 	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
# 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
# 	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
# 	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
# 	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
# 	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
# 	at io.confluent.connect.jms.BaseJmsSinkTask.put(BaseJmsSinkTask.java:111)
# 	at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:604)
# 	at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:334)
# 	at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:235)
# 	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:204)
# 	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:199)
# 	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:254)
# 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
# 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
# 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
# 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
# 	at java.base/java.lang.Thread.run(Thread.java:829)
# Caused by: com.ibm.mq.MQException: JMSCMQ0001: IBM MQ call failed with compcode '2' ('MQCC_FAILED') reason '2009' ('MQRC_CONNECTION_BROKEN').
# 	at com.ibm.msg.client.wmq.common.internal.Reason.createException(Reason.java:203)
# 	... 33 more
# Caused by: com.ibm.mq.jmqi.JmqiException: CC=2;RC=2009;AMQ9206: Error sending data to host 'zazkia/192.168.112.4:49998 (zazkia)'. [1=com.ibm.mq.jmqi.JmqiException[CC=2;RC=2009],3=zazkia/192.168.112.4:49998 (zazkia),4=TCP,5=RemoteTCPConnection.send(byte [ ],int,int,int,int)]
# 	at com.ibm.mq.jmqi.remote.impl.RemoteTCPConnection.send(RemoteTCPConnection.java:1708)
# 	at com.ibm.mq.jmqi.remote.impl.RemoteConnection.wrapSend(RemoteConnection.java:2976)
# 	at com.ibm.mq.jmqi.remote.impl.RemoteConnection.sendTSH(RemoteConnection.java:2742)
# 	at com.ibm.mq.jmqi.remote.impl.RemoteSession.sendTSH(RemoteSession.java:775)
# 	at com.ibm.mq.jmqi.remote.impl.RemoteSession.sendTSH(RemoteSession.java:691)
# 	at com.ibm.mq.jmqi.remote.api.RemoteFAP.jmqiPutMessageWithProps(RemoteFAP.java:8143)
# 	at com.ibm.mq.jmqi.remote.api.RemoteFAP.jmqiPut(RemoteFAP.java:7037)
# 	at com.ibm.mq.ese.jmqi.InterceptedJmqiImpl.jmqiPut(InterceptedJmqiImpl.java:636)
# 	at com.ibm.mq.ese.jmqi.ESEJMQI.jmqiPut(ESEJMQI.java:637)
# 	at com.ibm.msg.client.wmq.internal.WMQMessageProducer$SpiIdentifiedProducerShadow.sendInternal(WMQMessageProducer.java:897)
# 	... 29 more
# Caused by: com.ibm.mq.jmqi.JmqiException: CC=2;RC=2009
# 	at com.ibm.mq.jmqi.remote.impl.RemoteConnection.asyncConnectionBroken(RemoteConnection.java:3837)
# 	at com.ibm.mq.jmqi.remote.impl.RemoteRcvThread.run(RemoteRcvThread.java:587)
# 	at com.ibm.msg.client.commonservices.workqueue.WorkQueueItem.runTask(WorkQueueItem.java:319)
# 	at com.ibm.msg.client.commonservices.workqueue.SimpleWorkQueueItem.runItem(SimpleWorkQueueItem.java:99)
# 	at com.ibm.msg.client.commonservices.workqueue.WorkQueueItem.run(WorkQueueItem.java:343)
# 	at com.ibm.msg.client.commonservices.workqueue.WorkQueueManager.runWorkQueueItem(WorkQueueManager.java:312)
# 	at com.ibm.msg.client.commonservices.j2se.workqueue.WorkQueueManagerImplementation$ThreadPoolWorker.run(WorkQueueManagerImplementation.java:1227)
# Caused by: com.ibm.mq.jmqi.JmqiException: CC=2;RC=2009;AMQ9208: Error on receive from host 'zazkia/192.168.112.4:49998 (zazkia)'. [1=-1,2=ffffffff,3=zazkia/192.168.112.4:49998 (zazkia),4=TCP]
# 	at com.ibm.mq.jmqi.remote.impl.RemoteRcvThread.receiveBuffer(RemoteRcvThread.java:796)
# 	at com.ibm.mq.jmqi.remote.impl.RemoteRcvThread.receiveOneTSH(RemoteRcvThread.java:739)
# 	at com.ibm.mq.jmqi.remote.impl.RemoteRcvThread.run(RemoteRcvThread.java:156)
# 	... 5 more
# [2022-02-04 14:32:45,933] DEBUG [ibm-mq-sink4|task-0] Start exponential (0-86400000 ms) backoff of 00:00:00.112 before another attempt (io.confluent.connect.utils.retry.RetryCounter:361)
# [2022-02-04 14:32:45,933] TRACE [ibm-mq-sink4|task-0] Sleeping for 00:00:00.112ms, 112ms remaining (io.confluent.connect.utils.retry.RetryCounter:412)
# [2022-02-04 14:32:46,046] DEBUG [ibm-mq-sink4|task-0] Completed exponential (0-86400000 ms) backoff of 00:00:00.112 (io.confluent.connect.utils.retry.RetryCounter:373)
# [2022-02-04 14:32:46,046] WARN [ibm-mq-sink4|task-0] Could not produce message. Will retry for 60000 millis (io.confluent.connect.jms.BaseJmsSinkTask:182)
# com.ibm.msg.client.jms.DetailedJMSException: JMSWMQ2007: Failed to send a message to destination 'DEV.QUEUE.1'.
# JMS attempted to perform an MQPUT or MQPUT1; however IBM MQ reported an error.
# Use the linked exception to determine the cause of this error.
# 	at com.ibm.msg.client.wmq.common.internal.Reason.reasonToException(Reason.java:595)
# 	at com.ibm.msg.client.wmq.common.internal.Reason.createException(Reason.java:215)
# 	at com.ibm.msg.client.wmq.internal.WMQMessageProducer.checkJmqiCallSuccess(WMQMessageProducer.java:1293)
# 	at com.ibm.msg.client.wmq.internal.WMQMessageProducer.checkJmqiCallSuccess(WMQMessageProducer.java:1250)
# 	at com.ibm.msg.client.wmq.internal.WMQMessageProducer.access$800(WMQMessageProducer.java:76)
# 	at com.ibm.msg.client.wmq.internal.WMQMessageProducer$SpiIdentifiedProducerShadow.sendInternal(WMQMessageProducer.java:911)
# 	at com.ibm.msg.client.wmq.internal.WMQMessageProducer$ProducerShadow.send(WMQMessageProducer.java:567)
# 	at com.ibm.msg.client.wmq.internal.WMQMessageProducer.send(WMQMessageProducer.java:1433)
# 	at com.ibm.msg.client.jms.internal.JmsMessageProducerImpl.sendMessage(JmsMessageProducerImpl.java:855)
# 	at com.ibm.msg.client.jms.internal.JmsMessageProducerImpl.synchronousSendInternal(JmsMessageProducerImpl.java:2055)
# 	at com.ibm.msg.client.jms.internal.JmsMessageProducerImpl.sendInternal(JmsMessageProducerImpl.java:1993)
# 	at com.ibm.msg.client.jms.internal.JmsMessageProducerImpl.send(JmsMessageProducerImpl.java:1486)
# 	at com.ibm.mq.jms.MQMessageProducer.send(MQMessageProducer.java:293)
# 	at io.confluent.connect.jms.BaseJmsSinkTask.send(BaseJmsSinkTask.java:174)
# 	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
# 	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
# 	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655)
# 	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
# 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
# 	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
# 	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
# 	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
# 	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
# 	at io.confluent.connect.jms.BaseJmsSinkTask.put(BaseJmsSinkTask.java:111)
# 	at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:604)
# 	at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:334)
# 	at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:235)
# 	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:204)
# 	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:199)
# 	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:254)
# 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
# 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
# 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
# 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
# 	at java.base/java.lang.Thread.run(Thread.java:829)
# Caused by: com.ibm.mq.MQException: JMSCMQ0001: IBM MQ call failed with compcode '2' ('MQCC_FAILED') reason '2009' ('MQRC_CONNECTION_BROKEN').
# 	at com.ibm.msg.client.wmq.common.internal.Reason.createException(Reason.java:203)
# 	... 33 more
# Caused by: com.ibm.mq.jmqi.JmqiException: CC=2;RC=2009;AMQ9206: Error sending data to host 'zazkia/192.168.112.4:49998 (zazkia)'. [1=com.ibm.mq.jmqi.JmqiException[CC=2;RC=2009],3=zazkia/192.168.112.4:49998 (zazkia),4=TCP,5=RemoteTCPConnection.send(byte [ ],int,int,int,int)]
# 	at com.ibm.mq.jmqi.remote.impl.RemoteTCPConnection.send(RemoteTCPConnection.java:1708)
# 	at com.ibm.mq.jmqi.remote.impl.RemoteConnection.wrapSend(RemoteConnection.java:2976)
# 	at com.ibm.mq.jmqi.remote.impl.RemoteConnection.sendTSH(RemoteConnection.java:2742)
# 	at com.ibm.mq.jmqi.remote.impl.RemoteSession.sendTSH(RemoteSession.java:775)
# 	at com.ibm.mq.jmqi.remote.impl.RemoteSession.sendTSH(RemoteSession.java:691)
# 	at com.ibm.mq.jmqi.remote.api.RemoteFAP.jmqiPutMessageWithProps(RemoteFAP.java:8143)
# 	at com.ibm.mq.jmqi.remote.api.RemoteFAP.jmqiPut(RemoteFAP.java:7037)
# 	at com.ibm.mq.ese.jmqi.InterceptedJmqiImpl.jmqiPut(InterceptedJmqiImpl.java:636)
# 	at com.ibm.mq.ese.jmqi.ESEJMQI.jmqiPut(ESEJMQI.java:637)
# 	at com.ibm.msg.client.wmq.internal.WMQMessageProducer$SpiIdentifiedProducerShadow.sendInternal(WMQMessageProducer.java:897)
# 	... 29 more
# Caused by: com.ibm.mq.jmqi.JmqiException: CC=2;RC=2009
# 	at com.ibm.mq.jmqi.remote.impl.RemoteConnection.asyncConnectionBroken(RemoteConnection.java:3837)
# 	at com.ibm.mq.jmqi.remote.impl.RemoteRcvThread.run(RemoteRcvThread.java:587)
# 	at com.ibm.msg.client.commonservices.workqueue.WorkQueueItem.runTask(WorkQueueItem.java:319)
# 	at com.ibm.msg.client.commonservices.workqueue.SimpleWorkQueueItem.runItem(SimpleWorkQueueItem.java:99)
# 	at com.ibm.msg.client.commonservices.workqueue.WorkQueueItem.run(WorkQueueItem.java:343)
# 	at com.ibm.msg.client.commonservices.workqueue.WorkQueueManager.runWorkQueueItem(WorkQueueManager.java:312)
# 	at com.ibm.msg.client.commonservices.j2se.workqueue.WorkQueueManagerImplementation$ThreadPoolWorker.run(WorkQueueManagerImplementation.java:1227)
# Caused by: com.ibm.mq.jmqi.JmqiException: CC=2;RC=2009;AMQ9208: Error on receive from host 'zazkia/192.168.112.4:49998 (zazkia)'. [1=-1,2=ffffffff,3=zazkia/192.168.112.4:49998 (zazkia),4=TCP]
# 	at com.ibm.mq.jmqi.remote.impl.RemoteRcvThread.receiveBuffer(RemoteRcvThread.java:796)
# 	at com.ibm.mq.jmqi.remote.impl.RemoteRcvThread.receiveOneTSH(RemoteRcvThread.java:739)
# 	at com.ibm.mq.jmqi.remote.impl.RemoteRcvThread.run(RemoteRcvThread.java:156)
# 	... 5 more
# [2022-02-04 14:32:46,051] DEBUG [ibm-mq-sink4|task-0] Start exponential (0-86400000 ms) backoff of 00:00:00.038 before another attempt (io.confluent.connect.utils.retry.RetryCounter:361)
# [2022-02-04 14:32:46,051] TRACE [ibm-mq-sink4|task-0] Sleeping for 00:00:00.038ms, 38ms remaining (io.confluent.connect.utils.retry.RetryCounter:412)
# [2022-02-04 14:32:46,089] DEBUG [ibm-mq-sink4|task-0] Completed exponential (0-86400000 ms) backoff of 00:00:00.038 (io.confluent.connect.utils.retry.RetryCounter:373)
# [2022-02-04 14:32:46,090] WARN [ibm-mq-sink4|task-0] Could not produce message. Will retry for 60000 millis (io.confluent.connect.jms.BaseJmsSinkTask:182)
# com.ibm.msg.client.jms.DetailedJMSException: JMSWMQ2007: Failed to send a message to destination 'DEV.QUEUE.1'.
# JMS attempted to perform an MQPUT or MQPUT1; however IBM MQ reported an error.
# Use the linked exception to determine the cause of this error.
# 	at com.ibm.msg.client.wmq.common.internal.Reason.reasonToException(Reason.java:595)
# 	at com.ibm.msg.client.wmq.common.internal.Reason.createException(Reason.java:215)
# 	at com.ibm.msg.client.wmq.internal.WMQMessageProducer.checkJmqiCallSuccess(WMQMessageProducer.java:1293)
# 	at com.ibm.msg.client.wmq.internal.WMQMessageProducer.checkJmqiCallSuccess(WMQMessageProducer.java:1250)
# 	at com.ibm.msg.client.wmq.internal.WMQMessageProducer.access$800(WMQMessageProducer.java:76)
# 	at com.ibm.msg.client.wmq.internal.WMQMessageProducer$SpiIdentifiedProducerShadow.sendInternal(WMQMessageProducer.java:911)
# 	at com.ibm.msg.client.wmq.internal.WMQMessageProducer$ProducerShadow.send(WMQMessageProducer.java:567)
# 	at com.ibm.msg.client.wmq.internal.WMQMessageProducer.send(WMQMessageProducer.java:1433)
# 	at com.ibm.msg.client.jms.internal.JmsMessageProducerImpl.sendMessage(JmsMessageProducerImpl.java:855)
# 	at com.ibm.msg.client.jms.internal.JmsMessageProducerImpl.synchronousSendInternal(JmsMessageProducerImpl.java:2055)
# 	at com.ibm.msg.client.jms.internal.JmsMessageProducerImpl.sendInternal(JmsMessageProducerImpl.java:1993)
# 	at com.ibm.msg.client.jms.internal.JmsMessageProducerImpl.send(JmsMessageProducerImpl.java:1486)
# 	at com.ibm.mq.jms.MQMessageProducer.send(MQMessageProducer.java:293)
# 	at io.confluent.connect.jms.BaseJmsSinkTask.send(BaseJmsSinkTask.java:174)
# 	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
# 	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
# 	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655)
# 	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
# 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
# 	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
# 	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
# 	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
# 	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
# 	at io.confluent.connect.jms.BaseJmsSinkTask.put(BaseJmsSinkTask.java:111)
# 	at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:604)
# 	at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:334)
# 	at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:235)
# 	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:204)
# 	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:199)
# 	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:254)
# 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
# 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
# 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
# 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
# 	at java.base/java.lang.Thread.run(Thread.java:829)
# Caused by: com.ibm.mq.MQException: JMSCMQ0001: IBM MQ call failed with compcode '2' ('MQCC_FAILED') reason '2009' ('MQRC_CONNECTION_BROKEN').
# 	at com.ibm.msg.client.wmq.common.internal.Reason.createException(Reason.java:203)
# 	... 33 more
# Caused by: com.ibm.mq.jmqi.JmqiException: CC=2;RC=2009;AMQ9206: Error sending data to host 'zazkia/192.168.112.4:49998 (zazkia)'. [1=com.ibm.mq.jmqi.JmqiException[CC=2;RC=2009],3=zazkia/192.168.112.4:49998 (zazkia),4=TCP,5=RemoteTCPConnection.send(byte [ ],int,int,int,int)]
# 	at com.ibm.mq.jmqi.remote.impl.RemoteTCPConnection.send(RemoteTCPConnection.java:1708)
# 	at com.ibm.mq.jmqi.remote.impl.RemoteConnection.wrapSend(RemoteConnection.java:2976)
# 	at com.ibm.mq.jmqi.remote.impl.RemoteConnection.sendTSH(RemoteConnection.java:2742)
# 	at com.ibm.mq.jmqi.remote.impl.RemoteSession.sendTSH(RemoteSession.java:775)
# 	at com.ibm.mq.jmqi.remote.impl.RemoteSession.sendTSH(RemoteSession.java:691)
# 	at com.ibm.mq.jmqi.remote.api.RemoteFAP.jmqiPutMessageWithProps(RemoteFAP.java:8143)
# 	at com.ibm.mq.jmqi.remote.api.RemoteFAP.jmqiPut(RemoteFAP.java:7037)
# 	at com.ibm.mq.ese.jmqi.InterceptedJmqiImpl.jmqiPut(InterceptedJmqiImpl.java:636)
# 	at com.ibm.mq.ese.jmqi.ESEJMQI.jmqiPut(ESEJMQI.java:637)
# 	at com.ibm.msg.client.wmq.internal.WMQMessageProducer$SpiIdentifiedProducerShadow.sendInternal(WMQMessageProducer.java:897)
# 	... 29 more
# Caused by: com.ibm.mq.jmqi.JmqiException: CC=2;RC=2009
# 	at com.ibm.mq.jmqi.remote.impl.RemoteConnection.asyncConnectionBroken(RemoteConnection.java:3837)
# 	at com.ibm.mq.jmqi.remote.impl.RemoteRcvThread.run(RemoteRcvThread.java:587)
# 	at com.ibm.msg.client.commonservices.workqueue.WorkQueueItem.runTask(WorkQueueItem.java:319)
# 	at com.ibm.msg.client.commonservices.workqueue.SimpleWorkQueueItem.runItem(SimpleWorkQueueItem.java:99)
# 	at com.ibm.msg.client.commonservices.workqueue.WorkQueueItem.run(WorkQueueItem.java:343)
# 	at com.ibm.msg.client.commonservices.workqueue.WorkQueueManager.runWorkQueueItem(WorkQueueManager.java:312)
# 	at com.ibm.msg.client.commonservices.j2se.workqueue.WorkQueueManagerImplementation$ThreadPoolWorker.run(WorkQueueManagerImplementation.java:1227)
# Caused by: com.ibm.mq.jmqi.JmqiException: CC=2;RC=2009;AMQ9208: Error on receive from host 'zazkia/192.168.112.4:49998 (zazkia)'. [1=-1,2=ffffffff,3=zazkia/192.168.112.4:49998 (zazkia),4=TCP]
# 	at com.ibm.mq.jmqi.remote.impl.RemoteRcvThread.receiveBuffer(RemoteRcvThread.java:796)
# 	at com.ibm.mq.jmqi.remote.impl.RemoteRcvThread.receiveOneTSH(RemoteRcvThread.java:739)
# 	at com.ibm.mq.jmqi.remote.impl.RemoteRcvThread.run(RemoteRcvThread.java:156)
# 	... 5 more
# [2022-02-04 14:32:46,094] DEBUG [ibm-mq-sink4|task-0] Start exponential (0-86400000 ms) backoff of 00:00:00.104 before another attempt (io.confluent.connect.utils.retry.RetryCounter:361)
# [2022-02-04 14:32:46,094] TRACE [ibm-mq-sink4|task-0] Sleeping for 00:00:00.104ms, 104ms remaining (io.confluent.connect.utils.retry.RetryCounter:412)
# [2022-02-04 14:32:46,199] DEBUG [ibm-mq-sink4|task-0] Completed exponential (0-86400000 ms) backoff of 00:00:00.104 (io.confluent.connect.utils.retry.RetryCounter:373)
# [2022-02-04 14:32:46,199] WARN [ibm-mq-sink4|task-0] Could not produce message. Will retry for 60000 millis (io.confluent.connect.jms.BaseJmsSinkTask:182)
# com.ibm.msg.client.jms.DetailedJMSException: JMSWMQ2007: Failed to send a message to destination 'DEV.QUEUE.1'.
# JMS attempted to perform an MQPUT or MQPUT1; however IBM MQ reported an error.
# Use the linked exception to determine the cause of this error.
# 	at com.ibm.msg.client.wmq.common.internal.Reason.reasonToException(Reason.java:595)
# 	at com.ibm.msg.client.wmq.common.internal.Reason.createException(Reason.java:215)
# 	at com.ibm.msg.client.wmq.internal.WMQMessageProducer.checkJmqiCallSuccess(WMQMessageProducer.java:1293)
# 	at com.ibm.msg.client.wmq.internal.WMQMessageProducer.checkJmqiCallSuccess(WMQMessageProducer.java:1250)
# 	at com.ibm.msg.client.wmq.internal.WMQMessageProducer.access$800(WMQMessageProducer.java:76)
# 	at com.ibm.msg.client.wmq.internal.WMQMessageProducer$SpiIdentifiedProducerShadow.sendInternal(WMQMessageProducer.java:911)
# 	at com.ibm.msg.client.wmq.internal.WMQMessageProducer$ProducerShadow.send(WMQMessageProducer.java:567)
# 	at com.ibm.msg.client.wmq.internal.WMQMessageProducer.send(WMQMessageProducer.java:1433)
# 	at com.ibm.msg.client.jms.internal.JmsMessageProducerImpl.sendMessage(JmsMessageProducerImpl.java:855)
# 	at com.ibm.msg.client.jms.internal.JmsMessageProducerImpl.synchronousSendInternal(JmsMessageProducerImpl.java:2055)
# 	at com.ibm.msg.client.jms.internal.JmsMessageProducerImpl.sendInternal(JmsMessageProducerImpl.java:1993)
# 	at com.ibm.msg.client.jms.internal.JmsMessageProducerImpl.send(JmsMessageProducerImpl.java:1486)
# 	at com.ibm.mq.jms.MQMessageProducer.send(MQMessageProducer.java:293)
# 	at io.confluent.connect.jms.BaseJmsSinkTask.send(BaseJmsSinkTask.java:174)
# 	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
# 	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
# 	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655)
# 	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
# 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
# 	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
# 	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
# 	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
# 	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
# 	at io.confluent.connect.jms.BaseJmsSinkTask.put(BaseJmsSinkTask.java:111)
# 	at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:604)
# 	at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:334)
# 	at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:235)
# 	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:204)
# 	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:199)
# 	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:254)
# 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
# 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
# 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
# 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
# 	at java.base/java.lang.Thread.run(Thread.java:829)
# Caused by: com.ibm.mq.MQException: JMSCMQ0001: IBM MQ call failed with compcode '2' ('MQCC_FAILED') reason '2009' ('MQRC_CONNECTION_BROKEN').
# 	at com.ibm.msg.client.wmq.common.internal.Reason.createException(Reason.java:203)
# 	... 33 more
# Caused by: com.ibm.mq.jmqi.JmqiException: CC=2;RC=2009;AMQ9206: Error sending data to host 'zazkia/192.168.112.4:49998 (zazkia)'. [1=com.ibm.mq.jmqi.JmqiException[CC=2;RC=2009],3=zazkia/192.168.112.4:49998 (zazkia),4=TCP,5=RemoteTCPConnection.send(byte [ ],int,int,int,int)]
# 	at com.ibm.mq.jmqi.remote.impl.RemoteTCPConnection.send(RemoteTCPConnection.java:1708)
# 	at com.ibm.mq.jmqi.remote.impl.RemoteConnection.wrapSend(RemoteConnection.java:2976)
# 	at com.ibm.mq.jmqi.remote.impl.RemoteConnection.sendTSH(RemoteConnection.java:2742)
# 	at com.ibm.mq.jmqi.remote.impl.RemoteSession.sendTSH(RemoteSession.java:775)
# 	at com.ibm.mq.jmqi.remote.impl.RemoteSession.sendTSH(RemoteSession.java:691)
# 	at com.ibm.mq.jmqi.remote.api.RemoteFAP.jmqiPutMessageWithProps(RemoteFAP.java:8143)
# 	at com.ibm.mq.jmqi.remote.api.RemoteFAP.jmqiPut(RemoteFAP.java:7037)
# 	at com.ibm.mq.ese.jmqi.InterceptedJmqiImpl.jmqiPut(InterceptedJmqiImpl.java:636)
# 	at com.ibm.mq.ese.jmqi.ESEJMQI.jmqiPut(ESEJMQI.java:637)
# 	at com.ibm.msg.client.wmq.internal.WMQMessageProducer$SpiIdentifiedProducerShadow.sendInternal(WMQMessageProducer.java:897)
# 	... 29 more
# Caused by: com.ibm.mq.jmqi.JmqiException: CC=2;RC=2009
# 	at com.ibm.mq.jmqi.remote.impl.RemoteConnection.asyncConnectionBroken(RemoteConnection.java:3837)
# 	at com.ibm.mq.jmqi.remote.impl.RemoteRcvThread.run(RemoteRcvThread.java:587)
# 	at com.ibm.msg.client.commonservices.workqueue.WorkQueueItem.runTask(WorkQueueItem.java:319)
# 	at com.ibm.msg.client.commonservices.workqueue.SimpleWorkQueueItem.runItem(SimpleWorkQueueItem.java:99)
# 	at com.ibm.msg.client.commonservices.workqueue.WorkQueueItem.run(WorkQueueItem.java:343)
# 	at com.ibm.msg.client.commonservices.workqueue.WorkQueueManager.runWorkQueueItem(WorkQueueManager.java:312)
# 	at com.ibm.msg.client.commonservices.j2se.workqueue.WorkQueueManagerImplementation$ThreadPoolWorker.run(WorkQueueManagerImplementation.java:1227)
# Caused by: com.ibm.mq.jmqi.JmqiException: CC=2;RC=2009;AMQ9208: Error on receive from host 'zazkia/192.168.112.4:49998 (zazkia)'. [1=-1,2=ffffffff,3=zazkia/192.168.112.4:49998 (zazkia),4=TCP]
# 	at com.ibm.mq.jmqi.remote.impl.RemoteRcvThread.receiveBuffer(RemoteRcvThread.java:796)
# 	at com.ibm.mq.jmqi.remote.impl.RemoteRcvThread.receiveOneTSH(RemoteRcvThread.java:739)
# 	at com.ibm.mq.jmqi.remote.impl.RemoteRcvThread.run(RemoteRcvThread.java:156)
# 	... 5 more
# [2022-02-04 14:32:46,202] DEBUG [ibm-mq-sink4|task-0] Start exponential (0-86400000 ms) backoff of 00:00:00.395 before another attempt (io.confluent.connect.utils.retry.RetryCounter:361)
# [2022-02-04 14:32:46,202] TRACE [ibm-mq-sink4|task-0] Sleeping for 00:00:00.395ms, 395ms remaining (io.confluent.connect.utils.retry.RetryCounter:412)
# [2022-02-04 14:32:46,598] DEBUG [ibm-mq-sink4|task-0] Completed exponential (0-86400000 ms) backoff of 00:00:00.395 (io.confluent.connect.utils.retry.RetryCounter:373)
# [2022-02-04 14:32:46,598] WARN [ibm-mq-sink4|task-0] Could not produce message. Will retry for 60000 millis (io.confluent.connect.jms.BaseJmsSinkTask:182)
# com.ibm.msg.client.jms.DetailedJMSException: JMSWMQ2007: Failed to send a message to destination 'DEV.QUEUE.1'.
# JMS attempted to perform an MQPUT or MQPUT1; however IBM MQ reported an error.
# Use the linked exception to determine the cause of this error.
# 	at com.ibm.msg.client.wmq.common.internal.Reason.reasonToException(Reason.java:595)
# 	at com.ibm.msg.client.wmq.common.internal.Reason.createException(Reason.java:215)
# 	at com.ibm.msg.client.wmq.internal.WMQMessageProducer.checkJmqiCallSuccess(WMQMessageProducer.java:1293)
# 	at com.ibm.msg.client.wmq.internal.WMQMessageProducer.checkJmqiCallSuccess(WMQMessageProducer.java:1250)
# 	at com.ibm.msg.client.wmq.internal.WMQMessageProducer.access$800(WMQMessageProducer.java:76)
# 	at com.ibm.msg.client.wmq.internal.WMQMessageProducer$SpiIdentifiedProducerShadow.sendInternal(WMQMessageProducer.java:911)
# 	at com.ibm.msg.client.wmq.internal.WMQMessageProducer$ProducerShadow.send(WMQMessageProducer.java:567)
# 	at com.ibm.msg.client.wmq.internal.WMQMessageProducer.send(WMQMessageProducer.java:1433)
# 	at com.ibm.msg.client.jms.internal.JmsMessageProducerImpl.sendMessage(JmsMessageProducerImpl.java:855)
# 	at com.ibm.msg.client.jms.internal.JmsMessageProducerImpl.synchronousSendInternal(JmsMessageProducerImpl.java:2055)
# 	at com.ibm.msg.client.jms.internal.JmsMessageProducerImpl.sendInternal(JmsMessageProducerImpl.java:1993)
# 	at com.ibm.msg.client.jms.internal.JmsMessageProducerImpl.send(JmsMessageProducerImpl.java:1486)
# 	at com.ibm.mq.jms.MQMessageProducer.send(MQMessageProducer.java:293)
# 	at io.confluent.connect.jms.BaseJmsSinkTask.send(BaseJmsSinkTask.java:174)
# 	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
# 	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
# 	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655)
# 	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
# 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
# 	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
# 	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
# 	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
# 	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
# 	at io.confluent.connect.jms.BaseJmsSinkTask.put(BaseJmsSinkTask.java:111)
# 	at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:604)
# 	at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:334)
# 	at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:235)
# 	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:204)
# 	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:199)
# 	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:254)
# 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
# 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
# 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
# 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
# 	at java.base/java.lang.Thread.run(Thread.java:829)
# Caused by: com.ibm.mq.MQException: JMSCMQ0001: IBM MQ call failed with compcode '2' ('MQCC_FAILED') reason '2009' ('MQRC_CONNECTION_BROKEN').
# 	at com.ibm.msg.client.wmq.common.internal.Reason.createException(Reason.java:203)
# 	... 33 more
# Caused by: com.ibm.mq.jmqi.JmqiException: CC=2;RC=2009;AMQ9206: Error sending data to host 'zazkia/192.168.112.4:49998 (zazkia)'. [1=com.ibm.mq.jmqi.JmqiException[CC=2;RC=2009],3=zazkia/192.168.112.4:49998 (zazkia),4=TCP,5=RemoteTCPConnection.send(byte [ ],int,int,int,int)]
# 	at com.ibm.mq.jmqi.remote.impl.RemoteTCPConnection.send(RemoteTCPConnection.java:1708)
# 	at com.ibm.mq.jmqi.remote.impl.RemoteConnection.wrapSend(RemoteConnection.java:2976)
# 	at com.ibm.mq.jmqi.remote.impl.RemoteConnection.sendTSH(RemoteConnection.java:2742)
# 	at com.ibm.mq.jmqi.remote.impl.RemoteSession.sendTSH(RemoteSession.java:775)
# 	at com.ibm.mq.jmqi.remote.impl.RemoteSession.sendTSH(RemoteSession.java:691)
# 	at com.ibm.mq.jmqi.remote.api.RemoteFAP.jmqiPutMessageWithProps(RemoteFAP.java:8143)
# 	at com.ibm.mq.jmqi.remote.api.RemoteFAP.jmqiPut(RemoteFAP.java:7037)
# 	at com.ibm.mq.ese.jmqi.InterceptedJmqiImpl.jmqiPut(InterceptedJmqiImpl.java:636)
# 	at com.ibm.mq.ese.jmqi.ESEJMQI.jmqiPut(ESEJMQI.java:637)
# 	at com.ibm.msg.client.wmq.internal.WMQMessageProducer$SpiIdentifiedProducerShadow.sendInternal(WMQMessageProducer.java:897)
# 	... 29 more
# Caused by: com.ibm.mq.jmqi.JmqiException: CC=2;RC=2009
# 	at com.ibm.mq.jmqi.remote.impl.RemoteConnection.asyncConnectionBroken(RemoteConnection.java:3837)
# 	at com.ibm.mq.jmqi.remote.impl.RemoteRcvThread.run(RemoteRcvThread.java:587)
# 	at com.ibm.msg.client.commonservices.workqueue.WorkQueueItem.runTask(WorkQueueItem.java:319)
# 	at com.ibm.msg.client.commonservices.workqueue.SimpleWorkQueueItem.runItem(SimpleWorkQueueItem.java:99)
# 	at com.ibm.msg.client.commonservices.workqueue.WorkQueueItem.run(WorkQueueItem.java:343)
# 	at com.ibm.msg.client.commonservices.workqueue.WorkQueueManager.runWorkQueueItem(WorkQueueManager.java:312)
# 	at com.ibm.msg.client.commonservices.j2se.workqueue.WorkQueueManagerImplementation$ThreadPoolWorker.run(WorkQueueManagerImplementation.java:1227)
# Caused by: com.ibm.mq.jmqi.JmqiException: CC=2;RC=2009;AMQ9208: Error on receive from host 'zazkia/192.168.112.4:49998 (zazkia)'. [1=-1,2=ffffffff,3=zazkia/192.168.112.4:49998 (zazkia),4=TCP]
# 	at com.ibm.mq.jmqi.remote.impl.RemoteRcvThread.receiveBuffer(RemoteRcvThread.java:796)
# 	at com.ibm.mq.jmqi.remote.impl.RemoteRcvThread.receiveOneTSH(RemoteRcvThread.java:739)
# 	at com.ibm.mq.jmqi.remote.impl.RemoteRcvThread.run(RemoteRcvThread.java:156)
# 	... 5 more
# [2022-02-04 14:32:46,604] DEBUG [ibm-mq-sink4|task-0] Start exponential (0-86400000 ms) backoff of 00:00:01.207 before another attempt (io.confluent.connect.utils.retry.RetryCounter:361)
# [2022-02-04 14:32:46,605] TRACE [ibm-mq-sink4|task-0] Sleeping for 00:00:01.207ms, 1207ms remaining (io.confluent.connect.utils.retry.RetryCounter:412)
# [2022-02-04 14:32:47,813] DEBUG [ibm-mq-sink4|task-0] Completed exponential (0-86400000 ms) backoff of 00:00:01.207 (io.confluent.connect.utils.retry.RetryCounter:373)
# [2022-02-04 14:32:47,814] WARN [ibm-mq-sink4|task-0] Could not produce message. Will retry for 60000 millis (io.confluent.connect.jms.BaseJmsSinkTask:182)
# com.ibm.msg.client.jms.DetailedJMSException: JMSWMQ2007: Failed to send a message to destination 'DEV.QUEUE.1'.
# JMS attempted to perform an MQPUT or MQPUT1; however IBM MQ reported an error.
# Use the linked exception to determine the cause of this error.
# 	at com.ibm.msg.client.wmq.common.internal.Reason.reasonToException(Reason.java:595)
# 	at com.ibm.msg.client.wmq.common.internal.Reason.createException(Reason.java:215)
# 	at com.ibm.msg.client.wmq.internal.WMQMessageProducer.checkJmqiCallSuccess(WMQMessageProducer.java:1293)
# 	at com.ibm.msg.client.wmq.internal.WMQMessageProducer.checkJmqiCallSuccess(WMQMessageProducer.java:1250)
# 	at com.ibm.msg.client.wmq.internal.WMQMessageProducer.access$800(WMQMessageProducer.java:76)
# 	at com.ibm.msg.client.wmq.internal.WMQMessageProducer$SpiIdentifiedProducerShadow.sendInternal(WMQMessageProducer.java:911)
# 	at com.ibm.msg.client.wmq.internal.WMQMessageProducer$ProducerShadow.send(WMQMessageProducer.java:567)
# 	at com.ibm.msg.client.wmq.internal.WMQMessageProducer.send(WMQMessageProducer.java:1433)
# 	at com.ibm.msg.client.jms.internal.JmsMessageProducerImpl.sendMessage(JmsMessageProducerImpl.java:855)
# 	at com.ibm.msg.client.jms.internal.JmsMessageProducerImpl.synchronousSendInternal(JmsMessageProducerImpl.java:2055)
# 	at com.ibm.msg.client.jms.internal.JmsMessageProducerImpl.sendInternal(JmsMessageProducerImpl.java:1993)
# 	at com.ibm.msg.client.jms.internal.JmsMessageProducerImpl.send(JmsMessageProducerImpl.java:1486)
# 	at com.ibm.mq.jms.MQMessageProducer.send(MQMessageProducer.java:293)
# 	at io.confluent.connect.jms.BaseJmsSinkTask.send(BaseJmsSinkTask.java:174)
# 	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
# 	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
# 	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655)
# 	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
# 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
# 	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
# 	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
# 	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
# 	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
# 	at io.confluent.connect.jms.BaseJmsSinkTask.put(BaseJmsSinkTask.java:111)
# 	at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:604)
# 	at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:334)
# 	at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:235)
# 	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:204)
# 	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:199)
# 	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:254)
# 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
# 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
# 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
# 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
# 	at java.base/java.lang.Thread.run(Thread.java:829)
# Caused by: com.ibm.mq.MQException: JMSCMQ0001: IBM MQ call failed with compcode '2' ('MQCC_FAILED') reason '2009' ('MQRC_CONNECTION_BROKEN').
# 	at com.ibm.msg.client.wmq.common.internal.Reason.createException(Reason.java:203)
# 	... 33 more
# Caused by: com.ibm.mq.jmqi.JmqiException: CC=2;RC=2009;AMQ9206: Error sending data to host 'zazkia/192.168.112.4:49998 (zazkia)'. [1=com.ibm.mq.jmqi.JmqiException[CC=2;RC=2009],3=zazkia/192.168.112.4:49998 (zazkia),4=TCP,5=RemoteTCPConnection.send(byte [ ],int,int,int,int)]
# 	at com.ibm.mq.jmqi.remote.impl.RemoteTCPConnection.send(RemoteTCPConnection.java:1708)
# 	at com.ibm.mq.jmqi.remote.impl.RemoteConnection.wrapSend(RemoteConnection.java:2976)
# 	at com.ibm.mq.jmqi.remote.impl.RemoteConnection.sendTSH(RemoteConnection.java:2742)
# 	at com.ibm.mq.jmqi.remote.impl.RemoteSession.sendTSH(RemoteSession.java:775)
# 	at com.ibm.mq.jmqi.remote.impl.RemoteSession.sendTSH(RemoteSession.java:691)
# 	at com.ibm.mq.jmqi.remote.api.RemoteFAP.jmqiPutMessageWithProps(RemoteFAP.java:8143)
# 	at com.ibm.mq.jmqi.remote.api.RemoteFAP.jmqiPut(RemoteFAP.java:7037)
# 	at com.ibm.mq.ese.jmqi.InterceptedJmqiImpl.jmqiPut(InterceptedJmqiImpl.java:636)
# 	at com.ibm.mq.ese.jmqi.ESEJMQI.jmqiPut(ESEJMQI.java:637)
# 	at com.ibm.msg.client.wmq.internal.WMQMessageProducer$SpiIdentifiedProducerShadow.sendInternal(WMQMessageProducer.java:897)
# 	... 29 more
# Caused by: com.ibm.mq.jmqi.JmqiException: CC=2;RC=2009
# 	at com.ibm.mq.jmqi.remote.impl.RemoteConnection.asyncConnectionBroken(RemoteConnection.java:3837)
# 	at com.ibm.mq.jmqi.remote.impl.RemoteRcvThread.run(RemoteRcvThread.java:587)
# 	at com.ibm.msg.client.commonservices.workqueue.WorkQueueItem.runTask(WorkQueueItem.java:319)
# 	at com.ibm.msg.client.commonservices.workqueue.SimpleWorkQueueItem.runItem(SimpleWorkQueueItem.java:99)
# 	at com.ibm.msg.client.commonservices.workqueue.WorkQueueItem.run(WorkQueueItem.java:343)
# 	at com.ibm.msg.client.commonservices.workqueue.WorkQueueManager.runWorkQueueItem(WorkQueueManager.java:312)
# 	at com.ibm.msg.client.commonservices.j2se.workqueue.WorkQueueManagerImplementation$ThreadPoolWorker.run(WorkQueueManagerImplementation.java:1227)
# Caused by: com.ibm.mq.jmqi.JmqiException: CC=2;RC=2009;AMQ9208: Error on receive from host 'zazkia/192.168.112.4:49998 (zazkia)'. [1=-1,2=ffffffff,3=zazkia/192.168.112.4:49998 (zazkia),4=TCP]
# 	at com.ibm.mq.jmqi.remote.impl.RemoteRcvThread.receiveBuffer(RemoteRcvThread.java:796)
# 	at com.ibm.mq.jmqi.remote.impl.RemoteRcvThread.receiveOneTSH(RemoteRcvThread.java:739)
# 	at com.ibm.mq.jmqi.remote.impl.RemoteRcvThread.run(RemoteRcvThread.java:156)
# 	... 5 more
# [2022-02-04 14:32:47,821] DEBUG [ibm-mq-sink4|task-0] Start exponential (0-86400000 ms) backoff of 00:00:01.871 before another attempt (io.confluent.connect.utils.retry.RetryCounter:361)
# [2022-02-04 14:32:47,821] TRACE [ibm-mq-sink4|task-0] Sleeping for 00:00:01.871ms, 1871ms remaining (io.confluent.connect.utils.retry.RetryCounter:412)
# [2022-02-04 14:32:49,693] DEBUG [ibm-mq-sink4|task-0] Completed exponential (0-86400000 ms) backoff of 00:00:01.871 (io.confluent.connect.utils.retry.RetryCounter:373)
# [2022-02-04 14:32:49,693] WARN [ibm-mq-sink4|task-0] Could not produce message. Will retry for 60000 millis (io.confluent.connect.jms.BaseJmsSinkTask:182)
# com.ibm.msg.client.jms.DetailedJMSException: JMSWMQ2007: Failed to send a message to destination 'DEV.QUEUE.1'.
# JMS attempted to perform an MQPUT or MQPUT1; however IBM MQ reported an error.
# Use the linked exception to determine the cause of this error.
# 	at com.ibm.msg.client.wmq.common.internal.Reason.reasonToException(Reason.java:595)
# 	at com.ibm.msg.client.wmq.common.internal.Reason.createException(Reason.java:215)
# 	at com.ibm.msg.client.wmq.internal.WMQMessageProducer.checkJmqiCallSuccess(WMQMessageProducer.java:1293)
# 	at com.ibm.msg.client.wmq.internal.WMQMessageProducer.checkJmqiCallSuccess(WMQMessageProducer.java:1250)
# 	at com.ibm.msg.client.wmq.internal.WMQMessageProducer.access$800(WMQMessageProducer.java:76)
# 	at com.ibm.msg.client.wmq.internal.WMQMessageProducer$SpiIdentifiedProducerShadow.sendInternal(WMQMessageProducer.java:911)
# 	at com.ibm.msg.client.wmq.internal.WMQMessageProducer$ProducerShadow.send(WMQMessageProducer.java:567)
# 	at com.ibm.msg.client.wmq.internal.WMQMessageProducer.send(WMQMessageProducer.java:1433)
# 	at com.ibm.msg.client.jms.internal.JmsMessageProducerImpl.sendMessage(JmsMessageProducerImpl.java:855)
# 	at com.ibm.msg.client.jms.internal.JmsMessageProducerImpl.synchronousSendInternal(JmsMessageProducerImpl.java:2055)
# 	at com.ibm.msg.client.jms.internal.JmsMessageProducerImpl.sendInternal(JmsMessageProducerImpl.java:1993)
# 	at com.ibm.msg.client.jms.internal.JmsMessageProducerImpl.send(JmsMessageProducerImpl.java:1486)
# 	at com.ibm.mq.jms.MQMessageProducer.send(MQMessageProducer.java:293)
# 	at io.confluent.connect.jms.BaseJmsSinkTask.send(BaseJmsSinkTask.java:174)
# 	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
# 	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
# 	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655)
# 	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
# 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
# 	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
# 	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
# 	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
# 	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
# 	at io.confluent.connect.jms.BaseJmsSinkTask.put(BaseJmsSinkTask.java:111)
# 	at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:604)
# 	at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:334)
# 	at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:235)
# 	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:204)
# 	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:199)
# 	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:254)
# 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
# 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
# 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
# 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
# 	at java.base/java.lang.Thread.run(Thread.java:829)
# Caused by: com.ibm.mq.MQException: JMSCMQ0001: IBM MQ call failed with compcode '2' ('MQCC_FAILED') reason '2009' ('MQRC_CONNECTION_BROKEN').
# 	at com.ibm.msg.client.wmq.common.internal.Reason.createException(Reason.java:203)
# 	... 33 more
# Caused by: com.ibm.mq.jmqi.JmqiException: CC=2;RC=2009;AMQ9206: Error sending data to host 'zazkia/192.168.112.4:49998 (zazkia)'. [1=com.ibm.mq.jmqi.JmqiException[CC=2;RC=2009],3=zazkia/192.168.112.4:49998 (zazkia),4=TCP,5=RemoteTCPConnection.send(byte [ ],int,int,int,int)]
# 	at com.ibm.mq.jmqi.remote.impl.RemoteTCPConnection.send(RemoteTCPConnection.java:1708)
# 	at com.ibm.mq.jmqi.remote.impl.RemoteConnection.wrapSend(RemoteConnection.java:2976)
# 	at com.ibm.mq.jmqi.remote.impl.RemoteConnection.sendTSH(RemoteConnection.java:2742)
# 	at com.ibm.mq.jmqi.remote.impl.RemoteSession.sendTSH(RemoteSession.java:775)
# 	at com.ibm.mq.jmqi.remote.impl.RemoteSession.sendTSH(RemoteSession.java:691)
# 	at com.ibm.mq.jmqi.remote.api.RemoteFAP.jmqiPutMessageWithProps(RemoteFAP.java:8143)
# 	at com.ibm.mq.jmqi.remote.api.RemoteFAP.jmqiPut(RemoteFAP.java:7037)
# 	at com.ibm.mq.ese.jmqi.InterceptedJmqiImpl.jmqiPut(InterceptedJmqiImpl.java:636)
# 	at com.ibm.mq.ese.jmqi.ESEJMQI.jmqiPut(ESEJMQI.java:637)
# 	at com.ibm.msg.client.wmq.internal.WMQMessageProducer$SpiIdentifiedProducerShadow.sendInternal(WMQMessageProducer.java:897)
# 	... 29 more
# Caused by: com.ibm.mq.jmqi.JmqiException: CC=2;RC=2009
# 	at com.ibm.mq.jmqi.remote.impl.RemoteConnection.asyncConnectionBroken(RemoteConnection.java:3837)
# 	at com.ibm.mq.jmqi.remote.impl.RemoteRcvThread.run(RemoteRcvThread.java:587)
# 	at com.ibm.msg.client.commonservices.workqueue.WorkQueueItem.runTask(WorkQueueItem.java:319)
# 	at com.ibm.msg.client.commonservices.workqueue.SimpleWorkQueueItem.runItem(SimpleWorkQueueItem.java:99)
# 	at com.ibm.msg.client.commonservices.workqueue.WorkQueueItem.run(WorkQueueItem.java:343)
# 	at com.ibm.msg.client.commonservices.workqueue.WorkQueueManager.runWorkQueueItem(WorkQueueManager.java:312)
# 	at com.ibm.msg.client.commonservices.j2se.workqueue.WorkQueueManagerImplementation$ThreadPoolWorker.run(WorkQueueManagerImplementation.java:1227)
# Caused by: com.ibm.mq.jmqi.JmqiException: CC=2;RC=2009;AMQ9208: Error on receive from host 'zazkia/192.168.112.4:49998 (zazkia)'. [1=-1,2=ffffffff,3=zazkia/192.168.112.4:49998 (zazkia),4=TCP]
# 	at com.ibm.mq.jmqi.remote.impl.RemoteRcvThread.receiveBuffer(RemoteRcvThread.java:796)
# 	at com.ibm.mq.jmqi.remote.impl.RemoteRcvThread.receiveOneTSH(RemoteRcvThread.java:739)
# 	at com.ibm.mq.jmqi.remote.impl.RemoteRcvThread.run(RemoteRcvThread.java:156)
# 	... 5 more
# [2022-02-04 14:32:49,696] DEBUG [ibm-mq-sink4|task-0] Start exponential (0-86400000 ms) backoff of 00:00:04.898 before another attempt (io.confluent.connect.utils.retry.RetryCounter:361)
# [2022-02-04 14:32:49,696] TRACE [ibm-mq-sink4|task-0] Sleeping for 00:00:02.000ms, 4898ms remaining (io.confluent.connect.utils.retry.RetryCounter:412)
# [2022-02-04 14:32:51,696] TRACE [ibm-mq-sink4|task-0] Sleeping for 00:00:02.000ms, 2898ms remaining (io.confluent.connect.utils.retry.RetryCounter:412)
# [2022-02-04 14:32:53,662] TRACE [ibm-mq-sink4|task-0] Sleeping for 00:00:00.933ms, 933ms remaining (io.confluent.connect.utils.retry.RetryCounter:412)
# [2022-02-04 14:32:54,596] DEBUG [ibm-mq-sink4|task-0] Completed exponential (0-86400000 ms) backoff of 00:00:04.898 (io.confluent.connect.utils.retry.RetryCounter:373)
# [2022-02-04 14:32:54,596] WARN [ibm-mq-sink4|task-0] Could not produce message. Will retry for 60000 millis (io.confluent.connect.jms.BaseJmsSinkTask:182)
# com.ibm.msg.client.jms.DetailedJMSException: JMSWMQ2007: Failed to send a message to destination 'DEV.QUEUE.1'.
# JMS attempted to perform an MQPUT or MQPUT1; however IBM MQ reported an error.
# Use the linked exception to determine the cause of this error.
# 	at com.ibm.msg.client.wmq.common.internal.Reason.reasonToException(Reason.java:595)
# 	at com.ibm.msg.client.wmq.common.internal.Reason.createException(Reason.java:215)
# 	at com.ibm.msg.client.wmq.internal.WMQMessageProducer.checkJmqiCallSuccess(WMQMessageProducer.java:1293)
# 	at com.ibm.msg.client.wmq.internal.WMQMessageProducer.checkJmqiCallSuccess(WMQMessageProducer.java:1250)
# 	at com.ibm.msg.client.wmq.internal.WMQMessageProducer.access$800(WMQMessageProducer.java:76)
# 	at com.ibm.msg.client.wmq.internal.WMQMessageProducer$SpiIdentifiedProducerShadow.sendInternal(WMQMessageProducer.java:911)
# 	at com.ibm.msg.client.wmq.internal.WMQMessageProducer$ProducerShadow.send(WMQMessageProducer.java:567)
# 	at com.ibm.msg.client.wmq.internal.WMQMessageProducer.send(WMQMessageProducer.java:1433)
# 	at com.ibm.msg.client.jms.internal.JmsMessageProducerImpl.sendMessage(JmsMessageProducerImpl.java:855)
# 	at com.ibm.msg.client.jms.internal.JmsMessageProducerImpl.synchronousSendInternal(JmsMessageProducerImpl.java:2055)
# 	at com.ibm.msg.client.jms.internal.JmsMessageProducerImpl.sendInternal(JmsMessageProducerImpl.java:1993)
# 	at com.ibm.msg.client.jms.internal.JmsMessageProducerImpl.send(JmsMessageProducerImpl.java:1486)
# 	at com.ibm.mq.jms.MQMessageProducer.send(MQMessageProducer.java:293)
# 	at io.confluent.connect.jms.BaseJmsSinkTask.send(BaseJmsSinkTask.java:174)
# 	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
# 	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
# 	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655)
# 	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
# 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
# 	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
# 	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
# 	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
# 	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
# 	at io.confluent.connect.jms.BaseJmsSinkTask.put(BaseJmsSinkTask.java:111)
# 	at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:604)
# 	at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:334)
# 	at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:235)
# 	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:204)
# 	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:199)
# 	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:254)
# 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
# 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
# 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
# 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
# 	at java.base/java.lang.Thread.run(Thread.java:829)
# Caused by: com.ibm.mq.MQException: JMSCMQ0001: IBM MQ call failed with compcode '2' ('MQCC_FAILED') reason '2009' ('MQRC_CONNECTION_BROKEN').
# 	at com.ibm.msg.client.wmq.common.internal.Reason.createException(Reason.java:203)
# 	... 33 more
# Caused by: com.ibm.mq.jmqi.JmqiException: CC=2;RC=2009;AMQ9206: Error sending data to host 'zazkia/192.168.112.4:49998 (zazkia)'. [1=com.ibm.mq.jmqi.JmqiException[CC=2;RC=2009],3=zazkia/192.168.112.4:49998 (zazkia),4=TCP,5=RemoteTCPConnection.send(byte [ ],int,int,int,int)]
# 	at com.ibm.mq.jmqi.remote.impl.RemoteTCPConnection.send(RemoteTCPConnection.java:1708)
# 	at com.ibm.mq.jmqi.remote.impl.RemoteConnection.wrapSend(RemoteConnection.java:2976)
# 	at com.ibm.mq.jmqi.remote.impl.RemoteConnection.sendTSH(RemoteConnection.java:2742)
# 	at com.ibm.mq.jmqi.remote.impl.RemoteSession.sendTSH(RemoteSession.java:775)
# 	at com.ibm.mq.jmqi.remote.impl.RemoteSession.sendTSH(RemoteSession.java:691)
# 	at com.ibm.mq.jmqi.remote.api.RemoteFAP.jmqiPutMessageWithProps(RemoteFAP.java:8143)
# 	at com.ibm.mq.jmqi.remote.api.RemoteFAP.jmqiPut(RemoteFAP.java:7037)
# 	at com.ibm.mq.ese.jmqi.InterceptedJmqiImpl.jmqiPut(InterceptedJmqiImpl.java:636)
# 	at com.ibm.mq.ese.jmqi.ESEJMQI.jmqiPut(ESEJMQI.java:637)
# 	at com.ibm.msg.client.wmq.internal.WMQMessageProducer$SpiIdentifiedProducerShadow.sendInternal(WMQMessageProducer.java:897)
# 	... 29 more
# Caused by: com.ibm.mq.jmqi.JmqiException: CC=2;RC=2009
# 	at com.ibm.mq.jmqi.remote.impl.RemoteConnection.asyncConnectionBroken(RemoteConnection.java:3837)
# 	at com.ibm.mq.jmqi.remote.impl.RemoteRcvThread.run(RemoteRcvThread.java:587)
# 	at com.ibm.msg.client.commonservices.workqueue.WorkQueueItem.runTask(WorkQueueItem.java:319)
# 	at com.ibm.msg.client.commonservices.workqueue.SimpleWorkQueueItem.runItem(SimpleWorkQueueItem.java:99)
# 	at com.ibm.msg.client.commonservices.workqueue.WorkQueueItem.run(WorkQueueItem.java:343)
# 	at com.ibm.msg.client.commonservices.workqueue.WorkQueueManager.runWorkQueueItem(WorkQueueManager.java:312)
# 	at com.ibm.msg.client.commonservices.j2se.workqueue.WorkQueueManagerImplementation$ThreadPoolWorker.run(WorkQueueManagerImplementation.java:1227)
# Caused by: com.ibm.mq.jmqi.JmqiException: CC=2;RC=2009;AMQ9208: Error on receive from host 'zazkia/192.168.112.4:49998 (zazkia)'. [1=-1,2=ffffffff,3=zazkia/192.168.112.4:49998 (zazkia),4=TCP]
# 	at com.ibm.mq.jmqi.remote.impl.RemoteRcvThread.receiveBuffer(RemoteRcvThread.java:796)
# 	at com.ibm.mq.jmqi.remote.impl.RemoteRcvThread.receiveOneTSH(RemoteRcvThread.java:739)
# 	at com.ibm.mq.jmqi.remote.impl.RemoteRcvThread.run(RemoteRcvThread.java:156)
# 	... 5 more
# [2022-02-04 14:32:54,602] DEBUG [ibm-mq-sink4|task-0] Start exponential (0-86400000 ms) backoff of 00:00:08.461 before another attempt (io.confluent.connect.utils.retry.RetryCounter:361)
# [2022-02-04 14:32:54,602] TRACE [ibm-mq-sink4|task-0] Sleeping for 00:00:02.000ms, 8461ms remaining (io.confluent.connect.utils.retry.RetryCounter:412)
# [2022-02-04 14:32:56,603] TRACE [ibm-mq-sink4|task-0] Sleeping for 00:00:02.000ms, 6460ms remaining (io.confluent.connect.utils.retry.RetryCounter:412)
# [2022-02-04 14:32:58,603] TRACE [ibm-mq-sink4|task-0] Sleeping for 00:00:02.000ms, 4460ms remaining (io.confluent.connect.utils.retry.RetryCounter:412)
# [2022-02-04 14:33:00,604] TRACE [ibm-mq-sink4|task-0] Sleeping for 00:00:02.000ms, 2459ms remaining (io.confluent.connect.utils.retry.RetryCounter:412)
# [2022-02-04 14:33:02,605] TRACE [ibm-mq-sink4|task-0] Sleeping for 00:00:00.458ms, 458ms remaining (io.confluent.connect.utils.retry.RetryCounter:412)
# [2022-02-04 14:33:03,064] DEBUG [ibm-mq-sink4|task-0] Completed exponential (0-86400000 ms) backoff of 00:00:08.461 (io.confluent.connect.utils.retry.RetryCounter:373)
# [2022-02-04 14:33:03,065] WARN [ibm-mq-sink4|task-0] Could not produce message. Will retry for 60000 millis (io.confluent.connect.jms.BaseJmsSinkTask:182)
# com.ibm.msg.client.jms.DetailedJMSException: JMSWMQ2007: Failed to send a message to destination 'DEV.QUEUE.1'.
# JMS attempted to perform an MQPUT or MQPUT1; however IBM MQ reported an error.
# Use the linked exception to determine the cause of this error.
# 	at com.ibm.msg.client.wmq.common.internal.Reason.reasonToException(Reason.java:595)
# 	at com.ibm.msg.client.wmq.common.internal.Reason.createException(Reason.java:215)
# 	at com.ibm.msg.client.wmq.internal.WMQMessageProducer.checkJmqiCallSuccess(WMQMessageProducer.java:1293)
# 	at com.ibm.msg.client.wmq.internal.WMQMessageProducer.checkJmqiCallSuccess(WMQMessageProducer.java:1250)
# 	at com.ibm.msg.client.wmq.internal.WMQMessageProducer.access$800(WMQMessageProducer.java:76)
# 	at com.ibm.msg.client.wmq.internal.WMQMessageProducer$SpiIdentifiedProducerShadow.sendInternal(WMQMessageProducer.java:911)
# 	at com.ibm.msg.client.wmq.internal.WMQMessageProducer$ProducerShadow.send(WMQMessageProducer.java:567)
# 	at com.ibm.msg.client.wmq.internal.WMQMessageProducer.send(WMQMessageProducer.java:1433)
# 	at com.ibm.msg.client.jms.internal.JmsMessageProducerImpl.sendMessage(JmsMessageProducerImpl.java:855)
# 	at com.ibm.msg.client.jms.internal.JmsMessageProducerImpl.synchronousSendInternal(JmsMessageProducerImpl.java:2055)
# 	at com.ibm.msg.client.jms.internal.JmsMessageProducerImpl.sendInternal(JmsMessageProducerImpl.java:1993)
# 	at com.ibm.msg.client.jms.internal.JmsMessageProducerImpl.send(JmsMessageProducerImpl.java:1486)
# 	at com.ibm.mq.jms.MQMessageProducer.send(MQMessageProducer.java:293)
# 	at io.confluent.connect.jms.BaseJmsSinkTask.send(BaseJmsSinkTask.java:174)
# 	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
# 	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
# 	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655)
# 	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
# 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
# 	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
# 	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
# 	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
# 	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
# 	at io.confluent.connect.jms.BaseJmsSinkTask.put(BaseJmsSinkTask.java:111)
# 	at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:604)
# 	at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:334)
# 	at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:235)
# 	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:204)
# 	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:199)
# 	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:254)
# 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
# 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
# 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
# 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
# 	at java.base/java.lang.Thread.run(Thread.java:829)
# Caused by: com.ibm.mq.MQException: JMSCMQ0001: IBM MQ call failed with compcode '2' ('MQCC_FAILED') reason '2009' ('MQRC_CONNECTION_BROKEN').
# 	at com.ibm.msg.client.wmq.common.internal.Reason.createException(Reason.java:203)
# 	... 33 more
# Caused by: com.ibm.mq.jmqi.JmqiException: CC=2;RC=2009;AMQ9206: Error sending data to host 'zazkia/192.168.112.4:49998 (zazkia)'. [1=com.ibm.mq.jmqi.JmqiException[CC=2;RC=2009],3=zazkia/192.168.112.4:49998 (zazkia),4=TCP,5=RemoteTCPConnection.send(byte [ ],int,int,int,int)]
# 	at com.ibm.mq.jmqi.remote.impl.RemoteTCPConnection.send(RemoteTCPConnection.java:1708)
# 	at com.ibm.mq.jmqi.remote.impl.RemoteConnection.wrapSend(RemoteConnection.java:2976)
# 	at com.ibm.mq.jmqi.remote.impl.RemoteConnection.sendTSH(RemoteConnection.java:2742)
# 	at com.ibm.mq.jmqi.remote.impl.RemoteSession.sendTSH(RemoteSession.java:775)
# 	at com.ibm.mq.jmqi.remote.impl.RemoteSession.sendTSH(RemoteSession.java:691)
# 	at com.ibm.mq.jmqi.remote.api.RemoteFAP.jmqiPutMessageWithProps(RemoteFAP.java:8143)
# 	at com.ibm.mq.jmqi.remote.api.RemoteFAP.jmqiPut(RemoteFAP.java:7037)
# 	at com.ibm.mq.ese.jmqi.InterceptedJmqiImpl.jmqiPut(InterceptedJmqiImpl.java:636)
# 	at com.ibm.mq.ese.jmqi.ESEJMQI.jmqiPut(ESEJMQI.java:637)
# 	at com.ibm.msg.client.wmq.internal.WMQMessageProducer$SpiIdentifiedProducerShadow.sendInternal(WMQMessageProducer.java:897)
# 	... 29 more
# Caused by: com.ibm.mq.jmqi.JmqiException: CC=2;RC=2009
# 	at com.ibm.mq.jmqi.remote.impl.RemoteConnection.asyncConnectionBroken(RemoteConnection.java:3837)
# 	at com.ibm.mq.jmqi.remote.impl.RemoteRcvThread.run(RemoteRcvThread.java:587)
# 	at com.ibm.msg.client.commonservices.workqueue.WorkQueueItem.runTask(WorkQueueItem.java:319)
# 	at com.ibm.msg.client.commonservices.workqueue.SimpleWorkQueueItem.runItem(SimpleWorkQueueItem.java:99)
# 	at com.ibm.msg.client.commonservices.workqueue.WorkQueueItem.run(WorkQueueItem.java:343)
# 	at com.ibm.msg.client.commonservices.workqueue.WorkQueueManager.runWorkQueueItem(WorkQueueManager.java:312)
# 	at com.ibm.msg.client.commonservices.j2se.workqueue.WorkQueueManagerImplementation$ThreadPoolWorker.run(WorkQueueManagerImplementation.java:1227)
# Caused by: com.ibm.mq.jmqi.JmqiException: CC=2;RC=2009;AMQ9208: Error on receive from host 'zazkia/192.168.112.4:49998 (zazkia)'. [1=-1,2=ffffffff,3=zazkia/192.168.112.4:49998 (zazkia),4=TCP]
# 	at com.ibm.mq.jmqi.remote.impl.RemoteRcvThread.receiveBuffer(RemoteRcvThread.java:796)
# 	at com.ibm.mq.jmqi.remote.impl.RemoteRcvThread.receiveOneTSH(RemoteRcvThread.java:739)
# 	at com.ibm.mq.jmqi.remote.impl.RemoteRcvThread.run(RemoteRcvThread.java:156)
# 	... 5 more
# [2022-02-04 14:33:03,071] DEBUG [ibm-mq-sink4|task-0] Start exponential (0-86400000 ms) backoff of 00:00:22.481 before another attempt (io.confluent.connect.utils.retry.RetryCounter:361)
# [2022-02-04 14:33:03,071] TRACE [ibm-mq-sink4|task-0] Sleeping for 00:00:02.000ms, 22481ms remaining (io.confluent.connect.utils.retry.RetryCounter:412)
# [2022-02-04 14:33:05,072] TRACE [ibm-mq-sink4|task-0] Sleeping for 00:00:02.000ms, 20480ms remaining (io.confluent.connect.utils.retry.RetryCounter:412)
# [2022-02-04 14:33:07,073] TRACE [ibm-mq-sink4|task-0] Sleeping for 00:00:02.000ms, 18480ms remaining (io.confluent.connect.utils.retry.RetryCounter:412)
# [2022-02-04 14:33:09,073] TRACE [ibm-mq-sink4|task-0] Sleeping for 00:00:02.000ms, 16479ms remaining (io.confluent.connect.utils.retry.RetryCounter:412)
# [2022-02-04 14:33:11,074] TRACE [ibm-mq-sink4|task-0] Sleeping for 00:00:02.000ms, 14478ms remaining (io.confluent.connect.utils.retry.RetryCounter:412)
# [2022-02-04 14:33:13,075] TRACE [ibm-mq-sink4|task-0] Sleeping for 00:00:02.000ms, 12478ms remaining (io.confluent.connect.utils.retry.RetryCounter:412)
# [2022-02-04 14:33:15,075] TRACE [ibm-mq-sink4|task-0] Sleeping for 00:00:02.000ms, 10477ms remaining (io.confluent.connect.utils.retry.RetryCounter:412)
# [2022-02-04 14:33:17,076] TRACE [ibm-mq-sink4|task-0] Sleeping for 00:00:02.000ms, 8476ms remaining (io.confluent.connect.utils.retry.RetryCounter:412)
# [2022-02-04 14:33:19,076] TRACE [ibm-mq-sink4|task-0] Sleeping for 00:00:02.000ms, 6476ms remaining (io.confluent.connect.utils.retry.RetryCounter:412)
# [2022-02-04 14:33:21,077] TRACE [ibm-mq-sink4|task-0] Sleeping for 00:00:02.000ms, 4475ms remaining (io.confluent.connect.utils.retry.RetryCounter:412)
# [2022-02-04 14:33:23,042] TRACE [ibm-mq-sink4|task-0] Sleeping for 00:00:02.000ms, 2510ms remaining (io.confluent.connect.utils.retry.RetryCounter:412)
# [2022-02-04 14:33:25,044] TRACE [ibm-mq-sink4|task-0] Sleeping for 00:00:00.508ms, 508ms remaining (io.confluent.connect.utils.retry.RetryCounter:412)
# [2022-02-04 14:33:25,552] DEBUG [ibm-mq-sink4|task-0] Completed exponential (0-86400000 ms) backoff of 00:00:22.481 (io.confluent.connect.utils.retry.RetryCounter:373)
# [2022-02-04 14:33:25,553] WARN [ibm-mq-sink4|task-0] Could not produce message. Will retry for 60000 millis (io.confluent.connect.jms.BaseJmsSinkTask:182)
# com.ibm.msg.client.jms.DetailedJMSException: JMSWMQ2007: Failed to send a message to destination 'DEV.QUEUE.1'.
# JMS attempted to perform an MQPUT or MQPUT1; however IBM MQ reported an error.
# Use the linked exception to determine the cause of this error.
# 	at com.ibm.msg.client.wmq.common.internal.Reason.reasonToException(Reason.java:595)
# 	at com.ibm.msg.client.wmq.common.internal.Reason.createException(Reason.java:215)
# 	at com.ibm.msg.client.wmq.internal.WMQMessageProducer.checkJmqiCallSuccess(WMQMessageProducer.java:1293)
# 	at com.ibm.msg.client.wmq.internal.WMQMessageProducer.checkJmqiCallSuccess(WMQMessageProducer.java:1250)
# 	at com.ibm.msg.client.wmq.internal.WMQMessageProducer.access$800(WMQMessageProducer.java:76)
# 	at com.ibm.msg.client.wmq.internal.WMQMessageProducer$SpiIdentifiedProducerShadow.sendInternal(WMQMessageProducer.java:911)
# 	at com.ibm.msg.client.wmq.internal.WMQMessageProducer$ProducerShadow.send(WMQMessageProducer.java:567)
# 	at com.ibm.msg.client.wmq.internal.WMQMessageProducer.send(WMQMessageProducer.java:1433)
# 	at com.ibm.msg.client.jms.internal.JmsMessageProducerImpl.sendMessage(JmsMessageProducerImpl.java:855)
# 	at com.ibm.msg.client.jms.internal.JmsMessageProducerImpl.synchronousSendInternal(JmsMessageProducerImpl.java:2055)
# 	at com.ibm.msg.client.jms.internal.JmsMessageProducerImpl.sendInternal(JmsMessageProducerImpl.java:1993)
# 	at com.ibm.msg.client.jms.internal.JmsMessageProducerImpl.send(JmsMessageProducerImpl.java:1486)
# 	at com.ibm.mq.jms.MQMessageProducer.send(MQMessageProducer.java:293)
# 	at io.confluent.connect.jms.BaseJmsSinkTask.send(BaseJmsSinkTask.java:174)
# 	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
# 	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
# 	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655)
# 	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
# 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
# 	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
# 	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
# 	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
# 	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
# 	at io.confluent.connect.jms.BaseJmsSinkTask.put(BaseJmsSinkTask.java:111)
# 	at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:604)
# 	at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:334)
# 	at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:235)
# 	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:204)
# 	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:199)
# 	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:254)
# 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
# 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
# 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
# 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
# 	at java.base/java.lang.Thread.run(Thread.java:829)
# Caused by: com.ibm.mq.MQException: JMSCMQ0001: IBM MQ call failed with compcode '2' ('MQCC_FAILED') reason '2009' ('MQRC_CONNECTION_BROKEN').
# 	at com.ibm.msg.client.wmq.common.internal.Reason.createException(Reason.java:203)
# 	... 33 more
# Caused by: com.ibm.mq.jmqi.JmqiException: CC=2;RC=2009;AMQ9206: Error sending data to host 'zazkia/192.168.112.4:49998 (zazkia)'. [1=com.ibm.mq.jmqi.JmqiException[CC=2;RC=2009],3=zazkia/192.168.112.4:49998 (zazkia),4=TCP,5=RemoteTCPConnection.send(byte [ ],int,int,int,int)]
# 	at com.ibm.mq.jmqi.remote.impl.RemoteTCPConnection.send(RemoteTCPConnection.java:1708)
# 	at com.ibm.mq.jmqi.remote.impl.RemoteConnection.wrapSend(RemoteConnection.java:2976)
# 	at com.ibm.mq.jmqi.remote.impl.RemoteConnection.sendTSH(RemoteConnection.java:2742)
# 	at com.ibm.mq.jmqi.remote.impl.RemoteSession.sendTSH(RemoteSession.java:775)
# 	at com.ibm.mq.jmqi.remote.impl.RemoteSession.sendTSH(RemoteSession.java:691)
# 	at com.ibm.mq.jmqi.remote.api.RemoteFAP.jmqiPutMessageWithProps(RemoteFAP.java:8143)
# 	at com.ibm.mq.jmqi.remote.api.RemoteFAP.jmqiPut(RemoteFAP.java:7037)
# 	at com.ibm.mq.ese.jmqi.InterceptedJmqiImpl.jmqiPut(InterceptedJmqiImpl.java:636)
# 	at com.ibm.mq.ese.jmqi.ESEJMQI.jmqiPut(ESEJMQI.java:637)
# 	at com.ibm.msg.client.wmq.internal.WMQMessageProducer$SpiIdentifiedProducerShadow.sendInternal(WMQMessageProducer.java:897)
# 	... 29 more
# Caused by: com.ibm.mq.jmqi.JmqiException: CC=2;RC=2009
# 	at com.ibm.mq.jmqi.remote.impl.RemoteConnection.asyncConnectionBroken(RemoteConnection.java:3837)
# 	at com.ibm.mq.jmqi.remote.impl.RemoteRcvThread.run(RemoteRcvThread.java:587)
# 	at com.ibm.msg.client.commonservices.workqueue.WorkQueueItem.runTask(WorkQueueItem.java:319)
# 	at com.ibm.msg.client.commonservices.workqueue.SimpleWorkQueueItem.runItem(SimpleWorkQueueItem.java:99)
# 	at com.ibm.msg.client.commonservices.workqueue.WorkQueueItem.run(WorkQueueItem.java:343)
# 	at com.ibm.msg.client.commonservices.workqueue.WorkQueueManager.runWorkQueueItem(WorkQueueManager.java:312)
# 	at com.ibm.msg.client.commonservices.j2se.workqueue.WorkQueueManagerImplementation$ThreadPoolWorker.run(WorkQueueManagerImplementation.java:1227)
# Caused by: com.ibm.mq.jmqi.JmqiException: CC=2;RC=2009;AMQ9208: Error on receive from host 'zazkia/192.168.112.4:49998 (zazkia)'. [1=-1,2=ffffffff,3=zazkia/192.168.112.4:49998 (zazkia),4=TCP]
# 	at com.ibm.mq.jmqi.remote.impl.RemoteRcvThread.receiveBuffer(RemoteRcvThread.java:796)
# 	at com.ibm.mq.jmqi.remote.impl.RemoteRcvThread.receiveOneTSH(RemoteRcvThread.java:739)
# 	at com.ibm.mq.jmqi.remote.impl.RemoteRcvThread.run(RemoteRcvThread.java:156)
# 	... 5 more
# [2022-02-04 14:33:25,560] DEBUG [ibm-mq-sink4|task-0] Start exponential (0-86400000 ms) backoff of 00:00:14.572 before another attempt (io.confluent.connect.utils.retry.RetryCounter:361)
# [2022-02-04 14:33:25,561] TRACE [ibm-mq-sink4|task-0] Sleeping for 00:00:02.000ms, 14572ms remaining (io.confluent.connect.utils.retry.RetryCounter:412)
# [2022-02-04 14:33:27,562] TRACE [ibm-mq-sink4|task-0] Sleeping for 00:00:02.000ms, 12572ms remaining (io.confluent.connect.utils.retry.RetryCounter:412)
# [2022-02-04 14:33:29,562] TRACE [ibm-mq-sink4|task-0] Sleeping for 00:00:02.000ms, 10571ms remaining (io.confluent.connect.utils.retry.RetryCounter:412)
# [2022-02-04 14:33:31,563] TRACE [ibm-mq-sink4|task-0] Sleeping for 00:00:02.000ms, 8570ms remaining (io.confluent.connect.utils.retry.RetryCounter:412)
# [2022-02-04 14:33:33,564] TRACE [ibm-mq-sink4|task-0] Sleeping for 00:00:02.000ms, 6570ms remaining (io.confluent.connect.utils.retry.RetryCounter:412)
# [2022-02-04 14:33:35,564] TRACE [ibm-mq-sink4|task-0] Sleeping for 00:00:02.000ms, 4569ms remaining (io.confluent.connect.utils.retry.RetryCounter:412)
# [2022-02-04 14:33:37,565] TRACE [ibm-mq-sink4|task-0] Sleeping for 00:00:02.000ms, 2568ms remaining (io.confluent.connect.utils.retry.RetryCounter:412)
# [2022-02-04 14:33:39,565] TRACE [ibm-mq-sink4|task-0] Sleeping for 00:00:00.568ms, 568ms remaining (io.confluent.connect.utils.retry.RetryCounter:412)
# [2022-02-04 14:33:40,135] DEBUG [ibm-mq-sink4|task-0] Completed exponential (0-86400000 ms) backoff of 00:00:14.572 (io.confluent.connect.utils.retry.RetryCounter:373)
# [2022-02-04 14:33:40,135] WARN [ibm-mq-sink4|task-0] Could not produce message. Will retry for 60000 millis (io.confluent.connect.jms.BaseJmsSinkTask:182)
# com.ibm.msg.client.jms.DetailedJMSException: JMSWMQ2007: Failed to send a message to destination 'DEV.QUEUE.1'.
# JMS attempted to perform an MQPUT or MQPUT1; however IBM MQ reported an error.
# Use the linked exception to determine the cause of this error.
# 	at com.ibm.msg.client.wmq.common.internal.Reason.reasonToException(Reason.java:595)
# 	at com.ibm.msg.client.wmq.common.internal.Reason.createException(Reason.java:215)
# 	at com.ibm.msg.client.wmq.internal.WMQMessageProducer.checkJmqiCallSuccess(WMQMessageProducer.java:1293)
# 	at com.ibm.msg.client.wmq.internal.WMQMessageProducer.checkJmqiCallSuccess(WMQMessageProducer.java:1250)
# 	at com.ibm.msg.client.wmq.internal.WMQMessageProducer.access$800(WMQMessageProducer.java:76)
# 	at com.ibm.msg.client.wmq.internal.WMQMessageProducer$SpiIdentifiedProducerShadow.sendInternal(WMQMessageProducer.java:911)
# 	at com.ibm.msg.client.wmq.internal.WMQMessageProducer$ProducerShadow.send(WMQMessageProducer.java:567)
# 	at com.ibm.msg.client.wmq.internal.WMQMessageProducer.send(WMQMessageProducer.java:1433)
# 	at com.ibm.msg.client.jms.internal.JmsMessageProducerImpl.sendMessage(JmsMessageProducerImpl.java:855)
# 	at com.ibm.msg.client.jms.internal.JmsMessageProducerImpl.synchronousSendInternal(JmsMessageProducerImpl.java:2055)
# 	at com.ibm.msg.client.jms.internal.JmsMessageProducerImpl.sendInternal(JmsMessageProducerImpl.java:1993)
# 	at com.ibm.msg.client.jms.internal.JmsMessageProducerImpl.send(JmsMessageProducerImpl.java:1486)
# 	at com.ibm.mq.jms.MQMessageProducer.send(MQMessageProducer.java:293)
# 	at io.confluent.connect.jms.BaseJmsSinkTask.send(BaseJmsSinkTask.java:174)
# 	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
# 	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
# 	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655)
# 	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
# 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
# 	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
# 	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
# 	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
# 	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
# 	at io.confluent.connect.jms.BaseJmsSinkTask.put(BaseJmsSinkTask.java:111)
# 	at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:604)
# 	at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:334)
# 	at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:235)
# 	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:204)
# 	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:199)
# 	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:254)
# 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
# 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
# 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
# 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
# 	at java.base/java.lang.Thread.run(Thread.java:829)
# Caused by: com.ibm.mq.MQException: JMSCMQ0001: IBM MQ call failed with compcode '2' ('MQCC_FAILED') reason '2009' ('MQRC_CONNECTION_BROKEN').
# 	at com.ibm.msg.client.wmq.common.internal.Reason.createException(Reason.java:203)
# 	... 33 more
# Caused by: com.ibm.mq.jmqi.JmqiException: CC=2;RC=2009;AMQ9206: Error sending data to host 'zazkia/192.168.112.4:49998 (zazkia)'. [1=com.ibm.mq.jmqi.JmqiException[CC=2;RC=2009],3=zazkia/192.168.112.4:49998 (zazkia),4=TCP,5=RemoteTCPConnection.send(byte [ ],int,int,int,int)]
# 	at com.ibm.mq.jmqi.remote.impl.RemoteTCPConnection.send(RemoteTCPConnection.java:1708)
# 	at com.ibm.mq.jmqi.remote.impl.RemoteConnection.wrapSend(RemoteConnection.java:2976)
# 	at com.ibm.mq.jmqi.remote.impl.RemoteConnection.sendTSH(RemoteConnection.java:2742)
# 	at com.ibm.mq.jmqi.remote.impl.RemoteSession.sendTSH(RemoteSession.java:775)
# 	at com.ibm.mq.jmqi.remote.impl.RemoteSession.sendTSH(RemoteSession.java:691)
# 	at com.ibm.mq.jmqi.remote.api.RemoteFAP.jmqiPutMessageWithProps(RemoteFAP.java:8143)
# 	at com.ibm.mq.jmqi.remote.api.RemoteFAP.jmqiPut(RemoteFAP.java:7037)
# 	at com.ibm.mq.ese.jmqi.InterceptedJmqiImpl.jmqiPut(InterceptedJmqiImpl.java:636)
# 	at com.ibm.mq.ese.jmqi.ESEJMQI.jmqiPut(ESEJMQI.java:637)
# 	at com.ibm.msg.client.wmq.internal.WMQMessageProducer$SpiIdentifiedProducerShadow.sendInternal(WMQMessageProducer.java:897)
# 	... 29 more
# Caused by: com.ibm.mq.jmqi.JmqiException: CC=2;RC=2009
# 	at com.ibm.mq.jmqi.remote.impl.RemoteConnection.asyncConnectionBroken(RemoteConnection.java:3837)
# 	at com.ibm.mq.jmqi.remote.impl.RemoteRcvThread.run(RemoteRcvThread.java:587)
# 	at com.ibm.msg.client.commonservices.workqueue.WorkQueueItem.runTask(WorkQueueItem.java:319)
# 	at com.ibm.msg.client.commonservices.workqueue.SimpleWorkQueueItem.runItem(SimpleWorkQueueItem.java:99)
# 	at com.ibm.msg.client.commonservices.workqueue.WorkQueueItem.run(WorkQueueItem.java:343)
# 	at com.ibm.msg.client.commonservices.workqueue.WorkQueueManager.runWorkQueueItem(WorkQueueManager.java:312)
# 	at com.ibm.msg.client.commonservices.j2se.workqueue.WorkQueueManagerImplementation$ThreadPoolWorker.run(WorkQueueManagerImplementation.java:1227)
# Caused by: com.ibm.mq.jmqi.JmqiException: CC=2;RC=2009;AMQ9208: Error on receive from host 'zazkia/192.168.112.4:49998 (zazkia)'. [1=-1,2=ffffffff,3=zazkia/192.168.112.4:49998 (zazkia),4=TCP]
# 	at com.ibm.mq.jmqi.remote.impl.RemoteRcvThread.receiveBuffer(RemoteRcvThread.java:796)
# 	at com.ibm.mq.jmqi.remote.impl.RemoteRcvThread.receiveOneTSH(RemoteRcvThread.java:739)
# 	at com.ibm.mq.jmqi.remote.impl.RemoteRcvThread.run(RemoteRcvThread.java:156)
# 	... 5 more
# [2022-02-04 14:33:40,139] DEBUG [ibm-mq-sink4|task-0] Start exponential (0-86400000 ms) backoff of 00:00:05.682 before another attempt (io.confluent.connect.utils.retry.RetryCounter:361)
# [2022-02-04 14:33:40,140] TRACE [ibm-mq-sink4|task-0] Sleeping for 00:00:02.000ms, 5682ms remaining (io.confluent.connect.utils.retry.RetryCounter:412)
# [2022-02-04 14:33:42,141] TRACE [ibm-mq-sink4|task-0] Sleeping for 00:00:02.000ms, 3681ms remaining (io.confluent.connect.utils.retry.RetryCounter:412)
# [2022-02-04 14:33:44,141] TRACE [ibm-mq-sink4|task-0] Sleeping for 00:00:01.680ms, 1680ms remaining (io.confluent.connect.utils.retry.RetryCounter:412)
# [2022-02-04 14:33:45,822] DEBUG [ibm-mq-sink4|task-0] Completed exponential (0-86400000 ms) backoff of 00:00:05.682 (io.confluent.connect.utils.retry.RetryCounter:373)
# [2022-02-04 14:33:45,822] WARN [ibm-mq-sink4|task-0] Could not produce message. Will retry for 60000 millis (io.confluent.connect.jms.BaseJmsSinkTask:182)
# com.ibm.msg.client.jms.DetailedJMSException: JMSWMQ2007: Failed to send a message to destination 'DEV.QUEUE.1'.
# JMS attempted to perform an MQPUT or MQPUT1; however IBM MQ reported an error.
# Use the linked exception to determine the cause of this error.
# 	at com.ibm.msg.client.wmq.common.internal.Reason.reasonToException(Reason.java:595)
# 	at com.ibm.msg.client.wmq.common.internal.Reason.createException(Reason.java:215)
# 	at com.ibm.msg.client.wmq.internal.WMQMessageProducer.checkJmqiCallSuccess(WMQMessageProducer.java:1293)
# 	at com.ibm.msg.client.wmq.internal.WMQMessageProducer.checkJmqiCallSuccess(WMQMessageProducer.java:1250)
# 	at com.ibm.msg.client.wmq.internal.WMQMessageProducer.access$800(WMQMessageProducer.java:76)
# 	at com.ibm.msg.client.wmq.internal.WMQMessageProducer$SpiIdentifiedProducerShadow.sendInternal(WMQMessageProducer.java:911)
# 	at com.ibm.msg.client.wmq.internal.WMQMessageProducer$ProducerShadow.send(WMQMessageProducer.java:567)
# 	at com.ibm.msg.client.wmq.internal.WMQMessageProducer.send(WMQMessageProducer.java:1433)
# 	at com.ibm.msg.client.jms.internal.JmsMessageProducerImpl.sendMessage(JmsMessageProducerImpl.java:855)
# 	at com.ibm.msg.client.jms.internal.JmsMessageProducerImpl.synchronousSendInternal(JmsMessageProducerImpl.java:2055)
# 	at com.ibm.msg.client.jms.internal.JmsMessageProducerImpl.sendInternal(JmsMessageProducerImpl.java:1993)
# 	at com.ibm.msg.client.jms.internal.JmsMessageProducerImpl.send(JmsMessageProducerImpl.java:1486)
# 	at com.ibm.mq.jms.MQMessageProducer.send(MQMessageProducer.java:293)
# 	at io.confluent.connect.jms.BaseJmsSinkTask.send(BaseJmsSinkTask.java:174)
# 	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
# 	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
# 	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655)
# 	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
# 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
# 	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
# 	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
# 	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
# 	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
# 	at io.confluent.connect.jms.BaseJmsSinkTask.put(BaseJmsSinkTask.java:111)
# 	at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:604)
# 	at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:334)
# 	at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:235)
# 	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:204)
# 	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:199)
# 	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:254)
# 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
# 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
# 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
# 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
# 	at java.base/java.lang.Thread.run(Thread.java:829)
# Caused by: com.ibm.mq.MQException: JMSCMQ0001: IBM MQ call failed with compcode '2' ('MQCC_FAILED') reason '2009' ('MQRC_CONNECTION_BROKEN').
# 	at com.ibm.msg.client.wmq.common.internal.Reason.createException(Reason.java:203)
# 	... 33 more
# Caused by: com.ibm.mq.jmqi.JmqiException: CC=2;RC=2009;AMQ9206: Error sending data to host 'zazkia/192.168.112.4:49998 (zazkia)'. [1=com.ibm.mq.jmqi.JmqiException[CC=2;RC=2009],3=zazkia/192.168.112.4:49998 (zazkia),4=TCP,5=RemoteTCPConnection.send(byte [ ],int,int,int,int)]
# 	at com.ibm.mq.jmqi.remote.impl.RemoteTCPConnection.send(RemoteTCPConnection.java:1708)
# 	at com.ibm.mq.jmqi.remote.impl.RemoteConnection.wrapSend(RemoteConnection.java:2976)
# 	at com.ibm.mq.jmqi.remote.impl.RemoteConnection.sendTSH(RemoteConnection.java:2742)
# 	at com.ibm.mq.jmqi.remote.impl.RemoteSession.sendTSH(RemoteSession.java:775)
# 	at com.ibm.mq.jmqi.remote.impl.RemoteSession.sendTSH(RemoteSession.java:691)
# 	at com.ibm.mq.jmqi.remote.api.RemoteFAP.jmqiPutMessageWithProps(RemoteFAP.java:8143)
# 	at com.ibm.mq.jmqi.remote.api.RemoteFAP.jmqiPut(RemoteFAP.java:7037)
# 	at com.ibm.mq.ese.jmqi.InterceptedJmqiImpl.jmqiPut(InterceptedJmqiImpl.java:636)
# 	at com.ibm.mq.ese.jmqi.ESEJMQI.jmqiPut(ESEJMQI.java:637)
# 	at com.ibm.msg.client.wmq.internal.WMQMessageProducer$SpiIdentifiedProducerShadow.sendInternal(WMQMessageProducer.java:897)
# 	... 29 more
# Caused by: com.ibm.mq.jmqi.JmqiException: CC=2;RC=2009
# 	at com.ibm.mq.jmqi.remote.impl.RemoteConnection.asyncConnectionBroken(RemoteConnection.java:3837)
# 	at com.ibm.mq.jmqi.remote.impl.RemoteRcvThread.run(RemoteRcvThread.java:587)
# 	at com.ibm.msg.client.commonservices.workqueue.WorkQueueItem.runTask(WorkQueueItem.java:319)
# 	at com.ibm.msg.client.commonservices.workqueue.SimpleWorkQueueItem.runItem(SimpleWorkQueueItem.java:99)
# 	at com.ibm.msg.client.commonservices.workqueue.WorkQueueItem.run(WorkQueueItem.java:343)
# 	at com.ibm.msg.client.commonservices.workqueue.WorkQueueManager.runWorkQueueItem(WorkQueueManager.java:312)
# 	at com.ibm.msg.client.commonservices.j2se.workqueue.WorkQueueManagerImplementation$ThreadPoolWorker.run(WorkQueueManagerImplementation.java:1227)
# Caused by: com.ibm.mq.jmqi.JmqiException: CC=2;RC=2009;AMQ9208: Error on receive from host 'zazkia/192.168.112.4:49998 (zazkia)'. [1=-1,2=ffffffff,3=zazkia/192.168.112.4:49998 (zazkia),4=TCP]
# 	at com.ibm.mq.jmqi.remote.impl.RemoteRcvThread.receiveBuffer(RemoteRcvThread.java:796)
# 	at com.ibm.mq.jmqi.remote.impl.RemoteRcvThread.receiveOneTSH(RemoteRcvThread.java:739)
# 	at com.ibm.mq.jmqi.remote.impl.RemoteRcvThread.run(RemoteRcvThread.java:156)
# 	... 5 more
# [2022-02-04 14:33:45,827] ERROR [ibm-mq-sink4|task-0] Max retries exceeded (io.confluent.connect.jms.BaseJmsSinkTask:188)
# com.ibm.msg.client.jms.DetailedJMSException: JMSWMQ2007: Failed to send a message to destination 'DEV.QUEUE.1'.
# JMS attempted to perform an MQPUT or MQPUT1; however IBM MQ reported an error.
# Use the linked exception to determine the cause of this error.
# 	at com.ibm.msg.client.wmq.common.internal.Reason.reasonToException(Reason.java:595)
# 	at com.ibm.msg.client.wmq.common.internal.Reason.createException(Reason.java:215)
# 	at com.ibm.msg.client.wmq.internal.WMQMessageProducer.checkJmqiCallSuccess(WMQMessageProducer.java:1293)
# 	at com.ibm.msg.client.wmq.internal.WMQMessageProducer.checkJmqiCallSuccess(WMQMessageProducer.java:1250)
# 	at com.ibm.msg.client.wmq.internal.WMQMessageProducer.access$800(WMQMessageProducer.java:76)
# 	at com.ibm.msg.client.wmq.internal.WMQMessageProducer$SpiIdentifiedProducerShadow.sendInternal(WMQMessageProducer.java:911)
# 	at com.ibm.msg.client.wmq.internal.WMQMessageProducer$ProducerShadow.send(WMQMessageProducer.java:567)
# 	at com.ibm.msg.client.wmq.internal.WMQMessageProducer.send(WMQMessageProducer.java:1433)
# 	at com.ibm.msg.client.jms.internal.JmsMessageProducerImpl.sendMessage(JmsMessageProducerImpl.java:855)
# 	at com.ibm.msg.client.jms.internal.JmsMessageProducerImpl.synchronousSendInternal(JmsMessageProducerImpl.java:2055)
# 	at com.ibm.msg.client.jms.internal.JmsMessageProducerImpl.sendInternal(JmsMessageProducerImpl.java:1993)
# 	at com.ibm.msg.client.jms.internal.JmsMessageProducerImpl.send(JmsMessageProducerImpl.java:1486)
# 	at com.ibm.mq.jms.MQMessageProducer.send(MQMessageProducer.java:293)
# 	at io.confluent.connect.jms.BaseJmsSinkTask.send(BaseJmsSinkTask.java:174)
# 	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
# 	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
# 	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655)
# 	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
# 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
# 	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
# 	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
# 	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
# 	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
# 	at io.confluent.connect.jms.BaseJmsSinkTask.put(BaseJmsSinkTask.java:111)
# 	at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:604)
# 	at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:334)
# 	at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:235)
# 	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:204)
# 	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:199)
# 	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:254)
# 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
# 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
# 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
# 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
# 	at java.base/java.lang.Thread.run(Thread.java:829)
# Caused by: com.ibm.mq.MQException: JMSCMQ0001: IBM MQ call failed with compcode '2' ('MQCC_FAILED') reason '2009' ('MQRC_CONNECTION_BROKEN').
# 	at com.ibm.msg.client.wmq.common.internal.Reason.createException(Reason.java:203)
# 	... 33 more
# Caused by: com.ibm.mq.jmqi.JmqiException: CC=2;RC=2009;AMQ9206: Error sending data to host 'zazkia/192.168.112.4:49998 (zazkia)'. [1=com.ibm.mq.jmqi.JmqiException[CC=2;RC=2009],3=zazkia/192.168.112.4:49998 (zazkia),4=TCP,5=RemoteTCPConnection.send(byte [ ],int,int,int,int)]
# 	at com.ibm.mq.jmqi.remote.impl.RemoteTCPConnection.send(RemoteTCPConnection.java:1708)
# 	at com.ibm.mq.jmqi.remote.impl.RemoteConnection.wrapSend(RemoteConnection.java:2976)
# 	at com.ibm.mq.jmqi.remote.impl.RemoteConnection.sendTSH(RemoteConnection.java:2742)
# 	at com.ibm.mq.jmqi.remote.impl.RemoteSession.sendTSH(RemoteSession.java:775)
# 	at com.ibm.mq.jmqi.remote.impl.RemoteSession.sendTSH(RemoteSession.java:691)
# 	at com.ibm.mq.jmqi.remote.api.RemoteFAP.jmqiPutMessageWithProps(RemoteFAP.java:8143)
# 	at com.ibm.mq.jmqi.remote.api.RemoteFAP.jmqiPut(RemoteFAP.java:7037)
# 	at com.ibm.mq.ese.jmqi.InterceptedJmqiImpl.jmqiPut(InterceptedJmqiImpl.java:636)
# 	at com.ibm.mq.ese.jmqi.ESEJMQI.jmqiPut(ESEJMQI.java:637)
# 	at com.ibm.msg.client.wmq.internal.WMQMessageProducer$SpiIdentifiedProducerShadow.sendInternal(WMQMessageProducer.java:897)
# 	... 29 more
# Caused by: com.ibm.mq.jmqi.JmqiException: CC=2;RC=2009
# 	at com.ibm.mq.jmqi.remote.impl.RemoteConnection.asyncConnectionBroken(RemoteConnection.java:3837)
# 	at com.ibm.mq.jmqi.remote.impl.RemoteRcvThread.run(RemoteRcvThread.java:587)
# 	at com.ibm.msg.client.commonservices.workqueue.WorkQueueItem.runTask(WorkQueueItem.java:319)
# 	at com.ibm.msg.client.commonservices.workqueue.SimpleWorkQueueItem.runItem(SimpleWorkQueueItem.java:99)
# 	at com.ibm.msg.client.commonservices.workqueue.WorkQueueItem.run(WorkQueueItem.java:343)
# 	at com.ibm.msg.client.commonservices.workqueue.WorkQueueManager.runWorkQueueItem(WorkQueueManager.java:312)
# 	at com.ibm.msg.client.commonservices.j2se.workqueue.WorkQueueManagerImplementation$ThreadPoolWorker.run(WorkQueueManagerImplementation.java:1227)
# Caused by: com.ibm.mq.jmqi.JmqiException: CC=2;RC=2009;AMQ9208: Error on receive from host 'zazkia/192.168.112.4:49998 (zazkia)'. [1=-1,2=ffffffff,3=zazkia/192.168.112.4:49998 (zazkia),4=TCP]
# 	at com.ibm.mq.jmqi.remote.impl.RemoteRcvThread.receiveBuffer(RemoteRcvThread.java:796)
# 	at com.ibm.mq.jmqi.remote.impl.RemoteRcvThread.receiveOneTSH(RemoteRcvThread.java:739)
# 	at com.ibm.mq.jmqi.remote.impl.RemoteRcvThread.run(RemoteRcvThread.java:156)
# 	... 5 more
# [2022-02-04 14:33:45,830] WARN [ibm-mq-sink4|task-0] Could not close producer when refreshing connection. (io.confluent.connect.jms.BaseJmsSinkTask:196)
# com.ibm.msg.client.jms.DetailedJMSException: JMSWMQ2000: Failed to close queue 'DEV.QUEUE.1'.
# JMS attempted to close an IBM MQ destination, but encountered an error. The destination might already be closed, or another thread may be performing an MQGET while close() is called.
# Use the linked exception to determine the cause of this error. You may be able to perform the close() later.
# 	at com.ibm.msg.client.wmq.common.internal.Reason.reasonToException(Reason.java:595)
# 	at com.ibm.msg.client.wmq.common.internal.Reason.createException(Reason.java:215)
# 	at com.ibm.msg.client.wmq.internal.WMQMessageProducer.checkJmqiCallSuccess(WMQMessageProducer.java:1293)
# 	at com.ibm.msg.client.wmq.internal.WMQMessageProducer.access$400(WMQMessageProducer.java:76)
# 	at com.ibm.msg.client.wmq.internal.WMQMessageProducer$SpiIdentifiedProducerShadow.close(WMQMessageProducer.java:764)
# 	at com.ibm.msg.client.wmq.internal.WMQMessageProducer.close(WMQMessageProducer.java:1338)
# 	at com.ibm.msg.client.jms.internal.JmsMessageProducerImpl.close(JmsMessageProducerImpl.java:243)
# 	at com.ibm.msg.client.jms.internal.JmsMessageProducerImpl.close(JmsMessageProducerImpl.java:191)
# 	at com.ibm.mq.jms.MQQueueSender.close(MQQueueSender.java:78)
# 	at io.confluent.connect.jms.BaseJmsSinkTask.send(BaseJmsSinkTask.java:194)
# 	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
# 	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
# 	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655)
# 	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
# 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
# 	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
# 	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
# 	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
# 	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
# 	at io.confluent.connect.jms.BaseJmsSinkTask.put(BaseJmsSinkTask.java:111)
# 	at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:604)
# 	at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:334)
# 	at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:235)
# 	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:204)
# 	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:199)
# 	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:254)
# 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
# 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
# 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
# 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
# 	at java.base/java.lang.Thread.run(Thread.java:829)
# Caused by: com.ibm.mq.MQException: JMSCMQ0001: IBM MQ call failed with compcode '2' ('MQCC_FAILED') reason '2009' ('MQRC_CONNECTION_BROKEN').
# 	at com.ibm.msg.client.wmq.common.internal.Reason.createException(Reason.java:203)
# 	... 29 more
# Caused by: com.ibm.mq.jmqi.JmqiException: CC=2;RC=2009;AMQ9206: Error sending data to host 'zazkia/192.168.112.4:49998 (zazkia)'. [1=com.ibm.mq.jmqi.JmqiException[CC=2;RC=2009],3=zazkia/192.168.112.4:49998 (zazkia),4=TCP,5=RemoteTCPConnection.send(byte [ ],int,int,int,int)]
# 	at com.ibm.mq.jmqi.remote.impl.RemoteTCPConnection.send(RemoteTCPConnection.java:1708)
# 	at com.ibm.mq.jmqi.remote.impl.RemoteConnection.wrapSend(RemoteConnection.java:2976)
# 	at com.ibm.mq.jmqi.remote.impl.RemoteConnection.sendTSH(RemoteConnection.java:2742)
# 	at com.ibm.mq.jmqi.remote.impl.RemoteSession.sendTSH(RemoteSession.java:775)
# 	at com.ibm.mq.jmqi.remote.impl.RemoteSession.sendTSH(RemoteSession.java:691)
# 	at com.ibm.mq.jmqi.remote.api.RemoteFAP.MQCLOSE(RemoteFAP.java:6764)
# 	at com.ibm.mq.ese.jmqi.InterceptedJmqiImpl.MQCLOSE(InterceptedJmqiImpl.java:599)
# 	at com.ibm.mq.ese.jmqi.ESEJMQI.MQCLOSE(ESEJMQI.java:315)
# 	at com.ibm.msg.client.wmq.internal.WMQMessageProducer$SpiIdentifiedProducerShadow.close(WMQMessageProducer.java:734)
# 	... 26 more
# Caused by: com.ibm.mq.jmqi.JmqiException: CC=2;RC=2009
# 	at com.ibm.mq.jmqi.remote.impl.RemoteConnection.asyncConnectionBroken(RemoteConnection.java:3837)
# 	at com.ibm.mq.jmqi.remote.impl.RemoteRcvThread.run(RemoteRcvThread.java:587)
# 	at com.ibm.msg.client.commonservices.workqueue.WorkQueueItem.runTask(WorkQueueItem.java:319)
# 	at com.ibm.msg.client.commonservices.workqueue.SimpleWorkQueueItem.runItem(SimpleWorkQueueItem.java:99)
# 	at com.ibm.msg.client.commonservices.workqueue.WorkQueueItem.run(WorkQueueItem.java:343)
# 	at com.ibm.msg.client.commonservices.workqueue.WorkQueueManager.runWorkQueueItem(WorkQueueManager.java:312)
# 	at com.ibm.msg.client.commonservices.j2se.workqueue.WorkQueueManagerImplementation$ThreadPoolWorker.run(WorkQueueManagerImplementation.java:1227)
# Caused by: com.ibm.mq.jmqi.JmqiException: CC=2;RC=2009;AMQ9208: Error on receive from host 'zazkia/192.168.112.4:49998 (zazkia)'. [1=-1,2=ffffffff,3=zazkia/192.168.112.4:49998 (zazkia),4=TCP]
# 	at com.ibm.mq.jmqi.remote.impl.RemoteRcvThread.receiveBuffer(RemoteRcvThread.java:796)
# 	at com.ibm.mq.jmqi.remote.impl.RemoteRcvThread.receiveOneTSH(RemoteRcvThread.java:739)
# 	at com.ibm.mq.jmqi.remote.impl.RemoteRcvThread.run(RemoteRcvThread.java:156)
# 	... 5 more
# [2022-02-04 14:33:45,840] ERROR [ibm-mq-sink4|task-0] WorkerSinkTask{id=ibm-mq-sink4-0} Task threw an uncaught and unrecoverable exception. Task is being killed and will not recover until manually restarted. Error: Producer failed to write record from the 'sink-messages' Kafka Topic (Partition: 0, Offset: 1). (org.apache.kafka.connect.runtime.WorkerSinkTask:636)
# org.apache.kafka.connect.errors.ConnectException: Producer failed to write record from the 'sink-messages' Kafka Topic (Partition: 0, Offset: 1).
# 	at io.confluent.connect.jms.BaseJmsSinkTask.send(BaseJmsSinkTask.java:205)
# 	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
# 	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
# 	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655)
# 	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
# 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
# 	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
# 	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
# 	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
# 	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
# 	at io.confluent.connect.jms.BaseJmsSinkTask.put(BaseJmsSinkTask.java:111)
# 	at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:604)
# 	at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:334)
# 	at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:235)
# 	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:204)
# 	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:199)
# 	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:254)
# 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
# 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
# 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
# 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
# 	at java.base/java.lang.Thread.run(Thread.java:829)
# Caused by: com.ibm.msg.client.jms.DetailedJMSException: JMSWMQ2007: Failed to send a message to destination 'DEV.QUEUE.1'.
# JMS attempted to perform an MQPUT or MQPUT1; however IBM MQ reported an error.
# Use the linked exception to determine the cause of this error.
# 	at com.ibm.msg.client.wmq.common.internal.Reason.reasonToException(Reason.java:595)
# 	at com.ibm.msg.client.wmq.common.internal.Reason.createException(Reason.java:215)
# 	at com.ibm.msg.client.wmq.internal.WMQMessageProducer.checkJmqiCallSuccess(WMQMessageProducer.java:1293)
# 	at com.ibm.msg.client.wmq.internal.WMQMessageProducer.checkJmqiCallSuccess(WMQMessageProducer.java:1250)
# 	at com.ibm.msg.client.wmq.internal.WMQMessageProducer.access$800(WMQMessageProducer.java:76)
# 	at com.ibm.msg.client.wmq.internal.WMQMessageProducer$SpiIdentifiedProducerShadow.sendInternal(WMQMessageProducer.java:911)
# 	at com.ibm.msg.client.wmq.internal.WMQMessageProducer$ProducerShadow.send(WMQMessageProducer.java:567)
# 	at com.ibm.msg.client.wmq.internal.WMQMessageProducer.send(WMQMessageProducer.java:1433)
# 	at com.ibm.msg.client.jms.internal.JmsMessageProducerImpl.sendMessage(JmsMessageProducerImpl.java:855)
# 	at com.ibm.msg.client.jms.internal.JmsMessageProducerImpl.synchronousSendInternal(JmsMessageProducerImpl.java:2055)
# 	at com.ibm.msg.client.jms.internal.JmsMessageProducerImpl.sendInternal(JmsMessageProducerImpl.java:1993)
# 	at com.ibm.msg.client.jms.internal.JmsMessageProducerImpl.send(JmsMessageProducerImpl.java:1486)
# 	at com.ibm.mq.jms.MQMessageProducer.send(MQMessageProducer.java:293)
# 	at io.confluent.connect.jms.BaseJmsSinkTask.send(BaseJmsSinkTask.java:174)
# 	... 21 more
# Caused by: com.ibm.mq.MQException: JMSCMQ0001: IBM MQ call failed with compcode '2' ('MQCC_FAILED') reason '2009' ('MQRC_CONNECTION_BROKEN').
# 	at com.ibm.msg.client.wmq.common.internal.Reason.createException(Reason.java:203)
# 	... 33 more
# Caused by: com.ibm.mq.jmqi.JmqiException: CC=2;RC=2009;AMQ9206: Error sending data to host 'zazkia/192.168.112.4:49998 (zazkia)'. [1=com.ibm.mq.jmqi.JmqiException[CC=2;RC=2009],3=zazkia/192.168.112.4:49998 (zazkia),4=TCP,5=RemoteTCPConnection.send(byte [ ],int,int,int,int)]
# 	at com.ibm.mq.jmqi.remote.impl.RemoteTCPConnection.send(RemoteTCPConnection.java:1708)
# 	at com.ibm.mq.jmqi.remote.impl.RemoteConnection.wrapSend(RemoteConnection.java:2976)
# 	at com.ibm.mq.jmqi.remote.impl.RemoteConnection.sendTSH(RemoteConnection.java:2742)
# 	at com.ibm.mq.jmqi.remote.impl.RemoteSession.sendTSH(RemoteSession.java:775)
# 	at com.ibm.mq.jmqi.remote.impl.RemoteSession.sendTSH(RemoteSession.java:691)
# 	at com.ibm.mq.jmqi.remote.api.RemoteFAP.jmqiPutMessageWithProps(RemoteFAP.java:8143)
# 	at com.ibm.mq.jmqi.remote.api.RemoteFAP.jmqiPut(RemoteFAP.java:7037)
# 	at com.ibm.mq.ese.jmqi.InterceptedJmqiImpl.jmqiPut(InterceptedJmqiImpl.java:636)
# 	at com.ibm.mq.ese.jmqi.ESEJMQI.jmqiPut(ESEJMQI.java:637)
# 	at com.ibm.msg.client.wmq.internal.WMQMessageProducer$SpiIdentifiedProducerShadow.sendInternal(WMQMessageProducer.java:897)
# 	... 29 more
# Caused by: com.ibm.mq.jmqi.JmqiException: CC=2;RC=2009
# 	at com.ibm.mq.jmqi.remote.impl.RemoteConnection.asyncConnectionBroken(RemoteConnection.java:3837)
# 	at com.ibm.mq.jmqi.remote.impl.RemoteRcvThread.run(RemoteRcvThread.java:587)
# 	at com.ibm.msg.client.commonservices.workqueue.WorkQueueItem.runTask(WorkQueueItem.java:319)
# 	at com.ibm.msg.client.commonservices.workqueue.SimpleWorkQueueItem.runItem(SimpleWorkQueueItem.java:99)
# 	at com.ibm.msg.client.commonservices.workqueue.WorkQueueItem.run(WorkQueueItem.java:343)
# 	at com.ibm.msg.client.commonservices.workqueue.WorkQueueManager.runWorkQueueItem(WorkQueueManager.java:312)
# 	at com.ibm.msg.client.commonservices.j2se.workqueue.WorkQueueManagerImplementation$ThreadPoolWorker.run(WorkQueueManagerImplementation.java:1227)
# Caused by: com.ibm.mq.jmqi.JmqiException: CC=2;RC=2009;AMQ9208: Error on receive from host 'zazkia/192.168.112.4:49998 (zazkia)'. [1=-1,2=ffffffff,3=zazkia/192.168.112.4:49998 (zazkia),4=TCP]
# 	at com.ibm.mq.jmqi.remote.impl.RemoteRcvThread.receiveBuffer(RemoteRcvThread.java:796)
# 	at com.ibm.mq.jmqi.remote.impl.RemoteRcvThread.receiveOneTSH(RemoteRcvThread.java:739)
# 	at com.ibm.mq.jmqi.remote.impl.RemoteRcvThread.run(RemoteRcvThread.java:156)
# 	... 5 more
# [2022-02-04 14:33:45,841] ERROR [ibm-mq-sink4|task-0] WorkerSinkTask{id=ibm-mq-sink4-0} Task threw an uncaught and unrecoverable exception. Task is being killed and will not recover until manually restarted (org.apache.kafka.connect.runtime.WorkerTask:206)
# org.apache.kafka.connect.errors.ConnectException: Exiting WorkerSinkTask due to unrecoverable exception.
# 	at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:638)
# 	at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:334)
# 	at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:235)
# 	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:204)
# 	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:199)
# 	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:254)
# 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
# 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
# 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
# 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
# 	at java.base/java.lang.Thread.run(Thread.java:829)
# Caused by: org.apache.kafka.connect.errors.ConnectException: Producer failed to write record from the 'sink-messages' Kafka Topic (Partition: 0, Offset: 1).
# 	at io.confluent.connect.jms.BaseJmsSinkTask.send(BaseJmsSinkTask.java:205)
# 	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
# 	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
# 	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655)
# 	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
# 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
# 	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
# 	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
# 	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
# 	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
# 	at io.confluent.connect.jms.BaseJmsSinkTask.put(BaseJmsSinkTask.java:111)
# 	at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:604)
# 	... 10 more
# Caused by: com.ibm.msg.client.jms.DetailedJMSException: JMSWMQ2007: Failed to send a message to destination 'DEV.QUEUE.1'.
# JMS attempted to perform an MQPUT or MQPUT1; however IBM MQ reported an error.
# Use the linked exception to determine the cause of this error.
# 	at com.ibm.msg.client.wmq.common.internal.Reason.reasonToException(Reason.java:595)
# 	at com.ibm.msg.client.wmq.common.internal.Reason.createException(Reason.java:215)
# 	at com.ibm.msg.client.wmq.internal.WMQMessageProducer.checkJmqiCallSuccess(WMQMessageProducer.java:1293)
# 	at com.ibm.msg.client.wmq.internal.WMQMessageProducer.checkJmqiCallSuccess(WMQMessageProducer.java:1250)
# 	at com.ibm.msg.client.wmq.internal.WMQMessageProducer.access$800(WMQMessageProducer.java:76)
# 	at com.ibm.msg.client.wmq.internal.WMQMessageProducer$SpiIdentifiedProducerShadow.sendInternal(WMQMessageProducer.java:911)
# 	at com.ibm.msg.client.wmq.internal.WMQMessageProducer$ProducerShadow.send(WMQMessageProducer.java:567)
# 	at com.ibm.msg.client.wmq.internal.WMQMessageProducer.send(WMQMessageProducer.java:1433)
# 	at com.ibm.msg.client.jms.internal.JmsMessageProducerImpl.sendMessage(JmsMessageProducerImpl.java:855)
# 	at com.ibm.msg.client.jms.internal.JmsMessageProducerImpl.synchronousSendInternal(JmsMessageProducerImpl.java:2055)
# 	at com.ibm.msg.client.jms.internal.JmsMessageProducerImpl.sendInternal(JmsMessageProducerImpl.java:1993)
# 	at com.ibm.msg.client.jms.internal.JmsMessageProducerImpl.send(JmsMessageProducerImpl.java:1486)
# 	at com.ibm.mq.jms.MQMessageProducer.send(MQMessageProducer.java:293)
# 	at io.confluent.connect.jms.BaseJmsSinkTask.send(BaseJmsSinkTask.java:174)
# 	... 21 more
# Caused by: com.ibm.mq.MQException: JMSCMQ0001: IBM MQ call failed with compcode '2' ('MQCC_FAILED') reason '2009' ('MQRC_CONNECTION_BROKEN').
# 	at com.ibm.msg.client.wmq.common.internal.Reason.createException(Reason.java:203)
# 	... 33 more
# Caused by: com.ibm.mq.jmqi.JmqiException: CC=2;RC=2009;AMQ9206: Error sending data to host 'zazkia/192.168.112.4:49998 (zazkia)'. [1=com.ibm.mq.jmqi.JmqiException[CC=2;RC=2009],3=zazkia/192.168.112.4:49998 (zazkia),4=TCP,5=RemoteTCPConnection.send(byte [ ],int,int,int,int)]
# 	at com.ibm.mq.jmqi.remote.impl.RemoteTCPConnection.send(RemoteTCPConnection.java:1708)
# 	at com.ibm.mq.jmqi.remote.impl.RemoteConnection.wrapSend(RemoteConnection.java:2976)
# 	at com.ibm.mq.jmqi.remote.impl.RemoteConnection.sendTSH(RemoteConnection.java:2742)
# 	at com.ibm.mq.jmqi.remote.impl.RemoteSession.sendTSH(RemoteSession.java:775)
# 	at com.ibm.mq.jmqi.remote.impl.RemoteSession.sendTSH(RemoteSession.java:691)
# 	at com.ibm.mq.jmqi.remote.api.RemoteFAP.jmqiPutMessageWithProps(RemoteFAP.java:8143)
# 	at com.ibm.mq.jmqi.remote.api.RemoteFAP.jmqiPut(RemoteFAP.java:7037)
# 	at com.ibm.mq.ese.jmqi.InterceptedJmqiImpl.jmqiPut(InterceptedJmqiImpl.java:636)
# 	at com.ibm.mq.ese.jmqi.ESEJMQI.jmqiPut(ESEJMQI.java:637)
# 	at com.ibm.msg.client.wmq.internal.WMQMessageProducer$SpiIdentifiedProducerShadow.sendInternal(WMQMessageProducer.java:897)
# 	... 29 more
# Caused by: com.ibm.mq.jmqi.JmqiException: CC=2;RC=2009
# 	at com.ibm.mq.jmqi.remote.impl.RemoteConnection.asyncConnectionBroken(RemoteConnection.java:3837)
# 	at com.ibm.mq.jmqi.remote.impl.RemoteRcvThread.run(RemoteRcvThread.java:587)
# 	at com.ibm.msg.client.commonservices.workqueue.WorkQueueItem.runTask(WorkQueueItem.java:319)
# 	at com.ibm.msg.client.commonservices.workqueue.SimpleWorkQueueItem.runItem(SimpleWorkQueueItem.java:99)
# 	at com.ibm.msg.client.commonservices.workqueue.WorkQueueItem.run(WorkQueueItem.java:343)
# 	at com.ibm.msg.client.commonservices.workqueue.WorkQueueManager.runWorkQueueItem(WorkQueueManager.java:312)
# 	at com.ibm.msg.client.commonservices.j2se.workqueue.WorkQueueManagerImplementation$ThreadPoolWorker.run(WorkQueueManagerImplementation.java:1227)
# Caused by: com.ibm.mq.jmqi.JmqiException: CC=2;RC=2009;AMQ9208: Error on receive from host 'zazkia/192.168.112.4:49998 (zazkia)'. [1=-1,2=ffffffff,3=zazkia/192.168.112.4:49998 (zazkia),4=TCP]
# 	at com.ibm.mq.jmqi.remote.impl.RemoteRcvThread.receiveBuffer(RemoteRcvThread.java:796)
# 	at com.ibm.mq.jmqi.remote.impl.RemoteRcvThread.receiveOneTSH(RemoteRcvThread.java:739)
# 	at com.ibm.mq.jmqi.remote.impl.RemoteRcvThread.run(RemoteRcvThread.java:156)
# 	... 5 more